package pck_GUIs;

import java.awt.Color;
import static java.awt.Color.WHITE;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import pck_dao.PrestamoDAO;
import pck_model.PrestamoRow;
import pck_model.Usuario;
import pck_service.Session;

/**
 *
 * @author dieca
 */
public class DashboardView extends javax.swing.JFrame {

    int mouseinX, mouseinY;
    Rescalar escalar = new Rescalar();
    Usuario u = Session.get();
    String nombreUsuario = u.getNombre();
    String tarea = u.getTarea();
    String correo = u.getCorreo();
    String rol = u.getRolNombre();
    int id = u.getIdUsuario();
    LocalDate currentDate = LocalDate.now();

    /**
     * Creates new form login
     */
    public DashboardView() {
        initComponents();
        setLocationRelativeTo(null);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                escalar.escalarLabel(imgKintLogo, "/pck_img/kintLogo.png");
                escalar.escalarLabel(lbl_userSVG, "/pck_img/avatarIcon.png");
                escalar.escalarLabel(lbl_squareAvatar, "/pck_img/square_avatar.png");
            }
        });

        java.awt.event.ComponentAdapter resizeListener = new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                if (e.getComponent() == imgKintLogo) {
                    escalar.escalarLabel(imgKintLogo, "/pck_img/kintLogo.png");
                } else if (e.getComponent() == lbl_userSVG) {
                    escalar.escalarLabel(lbl_userSVG, "/pck_img/avatarIcon.png");
                }
            }
        };
        imgKintLogo.addComponentListener(resizeListener);
        lbl_userSVG.addComponentListener(resizeListener);

        setIconImage(new ImageIcon(getClass().getResource("/pck_img/favicon.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_bg = new javax.swing.JPanel();
        pan_menuLatIzq = new javax.swing.JPanel();
        imgKintLogo = new javax.swing.JLabel();
        btn_dashboard = new pck_customComponents.CustomButton();
        btn_inventario = new pck_customComponents.CustomButton();
        btn_solicitudes = new pck_customComponents.CustomButton();
        btn_usuarios = new pck_customComponents.CustomButton();
        btn_reportes = new pck_customComponents.CustomButton();
        btn_ayuda = new pck_customComponents.CustomButton();
        lbl_configuracion = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        pan_cabecera = new javax.swing.JPanel();
        lbl_navegador = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_nameholder = new javax.swing.JLabel();
        lbl_userSVG = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        tarjetaUsuario = new pck_customComponents.RoundedPanel();
        pill_estado = new pck_customComponents.PillLabel();
        lbl_squareAvatar = new javax.swing.JLabel();
        lbl_rol = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_idHolder = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_rol2 = new javax.swing.JLabel();
        lbl_rol3 = new javax.swing.JLabel();
        lbl_tarea = new javax.swing.JLabel();
        lbl_rol4 = new javax.swing.JLabel();
        lbl_cardName = new javax.swing.JLabel();
        panelPrestamos = new pck_customComponents.RoundedPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_prestamos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KINT - Dashboard");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_bg.setBackground(new java.awt.Color(245, 245, 245));
        pan_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_menuLatIzq.setBackground(new java.awt.Color(255, 255, 255));

        imgKintLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btn_dashboard.setText("📰 Dashboard");
        btn_dashboard.setToolTipText("Click para ir al Panel Principal");
        btn_dashboard.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_dashboard.setOver(true);
        btn_dashboard.setRadius(30);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        btn_inventario.setText("📦 Inventario");
        btn_inventario.setToolTipText("Click para ver Inventario");
        btn_inventario.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_inventario.setOver(true);
        btn_inventario.setRadius(30);
        btn_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventarioActionPerformed(evt);
            }
        });

        btn_solicitudes.setText("📩  Solicitudes");
        btn_solicitudes.setToolTipText("Click para ver Solicitudes (solo administradores)");
        btn_solicitudes.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_solicitudes.setOver(true);
        btn_solicitudes.setRadius(30);
        btn_solicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitudesActionPerformed(evt);
            }
        });

        btn_usuarios.setText("‍👨 Usuarios");
        btn_usuarios.setToolTipText("Click para ver usuarios (solo administradores)");
        btn_usuarios.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_usuarios.setOver(true);
        btn_usuarios.setRadius(30);
        btn_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariosActionPerformed(evt);
            }
        });

        btn_reportes.setText("📋 Reportes");
        btn_reportes.setToolTipText("Click para ver los Reportes (solo administradores)");
        btn_reportes.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_reportes.setOver(true);
        btn_reportes.setRadius(30);
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });

        btn_ayuda.setText("📞Ayuda");
        btn_ayuda.setToolTipText("Click para ir a ayuda");
        btn_ayuda.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_ayuda.setOver(true);
        btn_ayuda.setRadius(30);
        btn_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ayudaActionPerformed(evt);
            }
        });

        lbl_configuracion.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbl_configuracion.setText("⚙️ ️Configuración");
        lbl_configuracion.setToolTipText("Accede a la configuración general");
        lbl_configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_configuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_configuracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_configuracionMouseExited(evt);
            }
        });

        lbl_logout.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbl_logout.setText("📲 Cerrar Sesión");
        lbl_logout.setToolTipText("Cerrar sesión actual");
        lbl_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pan_menuLatIzqLayout = new javax.swing.GroupLayout(pan_menuLatIzq);
        pan_menuLatIzq.setLayout(pan_menuLatIzqLayout);
        pan_menuLatIzqLayout.setHorizontalGroup(
            pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgKintLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_menuLatIzqLayout.createSequentialGroup()
                        .addGroup(pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_solicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pan_menuLatIzqLayout.setVerticalGroup(
            pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(imgKintLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(lbl_configuracion)
                .addGap(18, 18, 18)
                .addComponent(lbl_logout)
                .addContainerGap())
        );

        pan_bg.add(pan_menuLatIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 800));

        pan_cabecera.setBackground(new java.awt.Color(64, 219, 255));
        pan_cabecera.setForeground(new java.awt.Color(99, 101, 105));
        pan_cabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pan_cabeceraMouseDragged(evt);
            }
        });
        pan_cabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pan_cabeceraMousePressed(evt);
            }
        });
        pan_cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_navegador.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        lbl_navegador.setForeground(new java.awt.Color(0, 0, 0));
        lbl_navegador.setText("Dashboard  /");
        pan_cabecera.add(lbl_navegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 440, 30));

        lbl_icon.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lbl_icon.setForeground(new java.awt.Color(0, 0, 0));
        lbl_icon.setText("🏠 / ");
        pan_cabecera.add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        lbl_exit.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(0, 0, 0));
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.setToolTipText("Salir");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_exitMousePressed(evt);
            }
        });
        pan_cabecera.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 40, 30));

        pan_bg.add(pan_cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 1020, 30));

        jSeparator1.setBackground(new java.awt.Color(184, 184, 184));
        jSeparator1.setForeground(new java.awt.Color(184, 184, 184));
        pan_bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 103, 1420, 10));

        lbl_nameholder.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        pan_bg.add(lbl_nameholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 80, 40));

        lbl_userSVG.setToolTipText("Ver perfil");
        lbl_userSVG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pan_bg.add(lbl_userSVG, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 40, 40, 40));

        lbl_username.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lbl_username.setText("Usuario:");
        pan_bg.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 80, 40));

        pill_estado.setText("Activo");

        lbl_rol.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lbl_rol.setForeground(new java.awt.Color(148, 148, 148));
        lbl_rol.setText("ROL");

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(148, 148, 148));
        jLabel2.setText("ID: ");

        lbl_idHolder.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lbl_idHolder.setForeground(new java.awt.Color(148, 148, 148));
        lbl_idHolder.setText("1");

        lbl_date.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(148, 148, 148));
        lbl_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_date.setText("1");

        lbl_email.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(0, 0, 0));
        lbl_email.setText("lbl");

        lbl_rol2.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lbl_rol2.setForeground(new java.awt.Color(148, 148, 148));
        lbl_rol2.setText("Tarea en curso");

        lbl_rol3.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lbl_rol3.setForeground(new java.awt.Color(148, 148, 148));
        lbl_rol3.setText("Nombre:");

        lbl_tarea.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lbl_tarea.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tarea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_tarea.setText("lbl");
        lbl_tarea.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_rol4.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lbl_rol4.setForeground(new java.awt.Color(148, 148, 148));
        lbl_rol4.setText("Correo:");

        lbl_cardName.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lbl_cardName.setForeground(new java.awt.Color(0, 0, 0));
        lbl_cardName.setText("lbl");

        javax.swing.GroupLayout tarjetaUsuarioLayout = new javax.swing.GroupLayout(tarjetaUsuario);
        tarjetaUsuario.setLayout(tarjetaUsuarioLayout);
        tarjetaUsuarioLayout.setHorizontalGroup(
            tarjetaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaUsuarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tarjetaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tarjetaUsuarioLayout.createSequentialGroup()
                        .addGroup(tarjetaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tarjetaUsuarioLayout.createSequentialGroup()
                                .addComponent(lbl_squareAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(tarjetaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tarjetaUsuarioLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_idHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pill_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tarjetaUsuarioLayout.createSequentialGroup()
                                .addGroup(tarjetaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_cardName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_rol2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                                .addGap(95, 95, 95)
                                .addComponent(lbl_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(109, 109, 109))
                    .addGroup(tarjetaUsuarioLayout.createSequentialGroup()
                        .addComponent(lbl_rol3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(lbl_rol4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        tarjetaUsuarioLayout.setVerticalGroup(
            tarjetaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaUsuarioLayout.createSequentialGroup()
                .addGroup(tarjetaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(tarjetaUsuarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(tarjetaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_rol)
                            .addComponent(pill_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tarjetaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbl_idHolder)
                            .addComponent(lbl_date)))
                    .addGroup(tarjetaUsuarioLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl_squareAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(tarjetaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_rol3)
                    .addComponent(lbl_rol4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tarjetaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cardName)
                    .addComponent(lbl_email))
                .addGap(18, 18, 18)
                .addComponent(lbl_rol2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_tarea, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        pan_bg.add(tarjetaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 520, 280));

        jtable_prestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_prestamos.setToolTipText("");
        jScrollPane1.setViewportView(jtable_prestamos);

        javax.swing.GroupLayout panelPrestamosLayout = new javax.swing.GroupLayout(panelPrestamos);
        panelPrestamos.setLayout(panelPrestamosLayout);
        panelPrestamosLayout.setHorizontalGroup(
            panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPrestamosLayout.setVerticalGroup(
            panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        pan_bg.add(panelPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 960, 380));

        getContentPane().add(pan_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void pan_cabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseinX, y - mouseinY);
    }//GEN-LAST:event_pan_cabeceraMouseDragged

    private void pan_cabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMousePressed
        mouseinX = evt.getX();
        mouseinY = evt.getY();
    }//GEN-LAST:event_pan_cabeceraMousePressed

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        if (!requerirRolPorId(1, 2)) {
            return;
        }
        JOptionPane.showMessageDialog(this, "Redirigiendo a gestión de usuarios.");
    }//GEN-LAST:event_btn_reportesActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventarioActionPerformed
        new InventoryView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_inventarioActionPerformed

    private void btn_solicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitudesActionPerformed
        if (!requerirRolPorId(1, 2)) {
            return;
        }
        JOptionPane.showMessageDialog(this, "Redirigiendo a gestión de usuarios.");
    }//GEN-LAST:event_btn_solicitudesActionPerformed

    private void btn_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariosActionPerformed
        if (!requerirRolPorId(1)) {
            return;
        }
        JOptionPane.showMessageDialog(this, "Redirigiendo a gestión de usuarios.");
    }//GEN-LAST:event_btn_usuariosActionPerformed

    private void btn_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ayudaActionPerformed

    private void lbl_configuracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_configuracionMouseEntered
        // TODO add your handling code here:
        lbl_configuracion.setForeground(new java.awt.Color(0, 178, 226));

    }//GEN-LAST:event_lbl_configuracionMouseEntered

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:
        int res;
        res = JOptionPane.showConfirmDialog(null, "¿Desea salir? \n", "Salir", JOptionPane.YES_NO_OPTION);
        if (res == 1) {
            return;
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered
        lbl_exit.setForeground(new java.awt.Color(0, 178, 226));
    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited
        lbl_exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbl_exitMouseExited

    private void lbl_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exitMousePressed

    private void lbl_configuracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_configuracionMouseExited
        lbl_configuracion.setForeground(Color.BLACK);

    }//GEN-LAST:event_lbl_configuracionMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lbl_nameholder.setText(nombreUsuario);
        lbl_idHolder.setText(String.valueOf(id));
        lbl_email.setText(correo);
        lbl_email.setToolTipText(correo);
        lbl_rol.setText(rol);
        lbl_tarea.setText(tarea);
        lbl_date.setText(currentDate.toString());
        lbl_cardName.setText(nombreUsuario);
        cargarTablaPrestamos();
        System.out.println(nombreUsuario);
    }//GEN-LAST:event_formWindowActivated

    // Autorizacion por ID de rol, la sintaxis de ... hace referencia a un parámetro multivariable, para que pueda poner desde 0...* argumentos
    //útil ya que en lugar de mandar a llamar la función y hacer 3 combinaciones diferentes de arreglos enteros, mejor paso directamente las constantes
    private boolean requerirRolPorId(int... idsPermitidos) {
        if (u == null) {
            JOptionPane.showMessageDialog(this, "Primero inicia sesión.", "Sesión requerida", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        int idRol = u.getIdRol();
        for (int id : idsPermitidos) {
            if (idRol == id) {
                return true;
            }
        }
        JOptionPane.showMessageDialog(this,
                "Solo usuarios autorizados pueden acceder a esta función.\nTu rol: " + u.getRolNombre(),
                "Acceso restringido", JOptionPane.WARNING_MESSAGE);
        return false;
    }

    private void cargarTablaPrestamos() {
        try {
            PrestamoDAO dao = new PrestamoDAO();
            java.util.List<PrestamoRow> rows;

            // Regla: Admin (1) y Supervisor (2) ven todas; Técnico (3) solo las suyas
            int rolId = u.getIdRol();
            if (rolId == 1 || rolId == 2) {
                rows = dao.listAll();
            } else {
                rows = dao.listByUsuario(u.getIdUsuario());
            }

            String[] cols = {"Folio", "Producto", "Cantidad", "Estado", "Prioridad", "Creado"};
            DefaultTableModel model = new DefaultTableModel(null, cols) {
                @Override
                public boolean isCellEditable(int r, int c) {
                    return false;
                }
            };

            if (rows == null || rows.isEmpty()) {
                model.addRow(new Object[]{"— No    —", "hay", "solicitudes", "registradas", "", ""});
                jtable_prestamos.setModel(model);
                jtable_prestamos.setAutoCreateRowSorter(false);
                jtable_prestamos.setRowSelectionAllowed(false);
                jtable_prestamos.setEnabled(false);
                javax.swing.table.DefaultTableCellRenderer gray = new javax.swing.table.DefaultTableCellRenderer();
                gray.setForeground(new java.awt.Color(120, 120, 120));
                gray.setFont(jtable_prestamos.getFont().deriveFont(java.awt.Font.ITALIC));
                jtable_prestamos.getColumnModel().getColumn(0).setCellRenderer(gray);
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");
            for (PrestamoRow r : rows) {
                model.addRow(new Object[]{
                    r.getFolio(),
                    r.getProducto(),
                    r.getCantidad(),
                    r.getEstado(),
                    r.getPrioridad(),
                    (r.getFechaCreacion() == null ? "" : sdf.format(r.getFechaCreacion()))
                });
            }

            jtable_prestamos.setModel(model);
            jtable_prestamos.setEnabled(true);
            jtable_prestamos.setRowSelectionAllowed(true);
            jtable_prestamos.setAutoCreateRowSorter(true);
            jtable_prestamos.setRowHeight(22);
            jtable_prestamos.getColumnModel().getColumn(0).setPreferredWidth(110);
            jtable_prestamos.getColumnModel().getColumn(1).setPreferredWidth(240);
            jtable_prestamos.getColumnModel().getColumn(2).setPreferredWidth(70);
            jtable_prestamos.getColumnModel().getColumn(3).setPreferredWidth(100);
            jtable_prestamos.getColumnModel().getColumn(4).setPreferredWidth(100);
            jtable_prestamos.getColumnModel().getColumn(5).setPreferredWidth(140);

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo cargar la tabla de préstamos.\n" + e.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardView().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pck_customComponents.CustomButton btn_ayuda;
    private pck_customComponents.CustomButton btn_dashboard;
    private pck_customComponents.CustomButton btn_inventario;
    private pck_customComponents.CustomButton btn_reportes;
    private pck_customComponents.CustomButton btn_solicitudes;
    private pck_customComponents.CustomButton btn_usuarios;
    private javax.swing.JLabel imgKintLogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtable_prestamos;
    private javax.swing.JLabel lbl_cardName;
    private javax.swing.JLabel lbl_configuracion;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_idHolder;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_nameholder;
    private javax.swing.JLabel lbl_navegador;
    private javax.swing.JLabel lbl_rol;
    private javax.swing.JLabel lbl_rol2;
    private javax.swing.JLabel lbl_rol3;
    private javax.swing.JLabel lbl_rol4;
    private javax.swing.JLabel lbl_squareAvatar;
    private javax.swing.JLabel lbl_tarea;
    private javax.swing.JLabel lbl_userSVG;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pan_bg;
    private javax.swing.JPanel pan_cabecera;
    private javax.swing.JPanel pan_menuLatIzq;
    private pck_customComponents.RoundedPanel panelPrestamos;
    private pck_customComponents.PillLabel pill_estado;
    private pck_customComponents.RoundedPanel tarjetaUsuario;
    // End of variables declaration//GEN-END:variables
}
