/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pck_GUIs;

import java.awt.Color;
import static java.awt.Color.WHITE;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author dieca
 */
public class DashboardView extends javax.swing.JFrame {

    int mouseinX, mouseinY;
    Rescalar escalar = new Rescalar();

    /**
     * Creates new form login
     */
    public DashboardView() {
        initComponents();
        setLocationRelativeTo(null);
        escalar.escalarLabel(imgKintLogo, "/pck_img/kintLogo.png");
        setIconImage(new ImageIcon(getClass().getResource("/pck_img/favicon.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_bg = new javax.swing.JPanel();
        pan_menuLatIzq = new javax.swing.JPanel();
        imgKintLogo = new javax.swing.JLabel();
        customButton1 = new pck_customBtn.CustomButton();
        pan_cabecera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KINT - Recuperación de contraseña");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_bg.setBackground(new java.awt.Color(245, 245, 245));
        pan_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_menuLatIzq.setBackground(new java.awt.Color(255, 255, 255));
        pan_menuLatIzq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgKintLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pan_menuLatIzq.add(imgKintLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 60));

        customButton1.setText("Dashboard");
        customButton1.setOver(true);
        customButton1.setRadius(50);
        customButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton1ActionPerformed(evt);
            }
        });
        pan_menuLatIzq.add(customButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 100, 40));

        pan_bg.add(pan_menuLatIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 830));

        pan_cabecera.setBackground(new java.awt.Color(64, 219, 255));
        pan_cabecera.setForeground(new java.awt.Color(99, 101, 105));
        pan_cabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pan_cabeceraMouseDragged(evt);
            }
        });
        pan_cabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pan_cabeceraMousePressed(evt);
            }
        });
        pan_cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Dashboard  /");
        pan_cabecera.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 440, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("🏠 / ");
        pan_cabecera.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        pan_bg.add(pan_cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1410, 30));

        jSeparator1.setBackground(new java.awt.Color(184, 184, 184));
        jSeparator1.setForeground(new java.awt.Color(184, 184, 184));
        pan_bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 1420, -1));

        getContentPane().add(pan_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pan_cabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseinX, y - mouseinY);
    }//GEN-LAST:event_pan_cabeceraMouseDragged

    private void pan_cabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMousePressed
        mouseinX = evt.getX();
        mouseinY = evt.getY();
    }//GEN-LAST:event_pan_cabeceraMousePressed

    private void customButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pck_customBtn.CustomButton customButton1;
    private javax.swing.JLabel imgKintLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pan_bg;
    private javax.swing.JPanel pan_cabecera;
    private javax.swing.JPanel pan_menuLatIzq;
    // End of variables declaration//GEN-END:variables
}
