package pck_GUIs;

import java.awt.Color;
import static java.awt.Color.WHITE;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import pck_dao.UsuarioDAO;
import pck_model.Usuario;
import pck_service.Session;

/**
 *
 * @author dieca
 */
public class EditUserView extends javax.swing.JFrame {

    private int mouseinX, mouseinY;
    private Rescalar escalar = new Rescalar();
    private Usuario u = Session.get();
    private String nombreUsuario = u.getNombre();
    private String tarea = u.getTarea();
    private String correo = u.getCorreo();
    private String rol = u.getRolNombre();
    private final UsuarioDAO usuarioDAO = new UsuarioDAO();
    private Usuario usuarioActual = null;
    private int idUsuario;

    LocalDate currentDate = LocalDate.now();

    /**
     * Creates new form login
     */
    public EditUserView(int idUsuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.idUsuario = idUsuario;
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                escalar.escalarLabel(imgKintLogo, "/pck_img/kintLogo.png");
                escalar.escalarLabel(lbl_userSVG, "/pck_img/avatarIcon.png");
            }
        });

        java.awt.event.ComponentAdapter resizeListener = new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                if (e.getComponent() == imgKintLogo) {
                    escalar.escalarLabel(imgKintLogo, "/pck_img/kintLogo.png");
                } else if (e.getComponent() == lbl_userSVG) {
                    escalar.escalarLabel(lbl_userSVG, "/pck_img/avatarIcon.png");
                }
            }
        };
        imgKintLogo.addComponentListener(resizeListener);
        lbl_userSVG.addComponentListener(resizeListener);

        setIconImage(new ImageIcon(getClass().getResource("/pck_img/favicon.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_bg = new javax.swing.JPanel();
        pan_menuLatIzq = new javax.swing.JPanel();
        imgKintLogo = new javax.swing.JLabel();
        btn_dashboard = new pck_customComponents.CustomButton();
        btn_inventario = new pck_customComponents.CustomButton();
        btn_solicitudes = new pck_customComponents.CustomButton();
        btn_usuarios = new pck_customComponents.CustomButton();
        btn_reportes = new pck_customComponents.CustomButton();
        btn_ayuda = new pck_customComponents.CustomButton();
        lbl_configuracion = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        pan_cabecera = new javax.swing.JPanel();
        lbl_icon = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        lbl_navegador1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_nameholder = new javax.swing.JLabel();
        lbl_userSVG = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        roundedPanel1 = new pck_customComponents.RoundedPanel();
        lbl_pass = new javax.swing.JLabel();
        tf_nombre = new pck_customComponents.RoundedTextField();
        lbl_navegador2 = new javax.swing.JLabel();
        cb_rol = new javax.swing.JComboBox<>();
        lbl_navegador3 = new javax.swing.JLabel();
        tf_correo = new pck_customComponents.RoundedTextField();
        lbl_navegador4 = new javax.swing.JLabel();
        tf_pass = new pck_customComponents.RoundedTextField();
        btn_generarPass = new pck_customComponents.CustomButton();
        checkb_activo = new javax.swing.JCheckBox();
        lbl_navegador5 = new javax.swing.JLabel();
        lbl_navegador6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_tarea = new pck_customComponents.RoundedTextArea();
        dc_fechaNacimiento = new com.toedter.calendar.JDateChooser();
        lbl_pass1 = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        btn_editar = new pck_customComponents.CustomButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KINT - Dashboard");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_bg.setBackground(new java.awt.Color(245, 245, 245));
        pan_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_menuLatIzq.setBackground(new java.awt.Color(255, 255, 255));

        imgKintLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btn_dashboard.setText("📰 Dashboard");
        btn_dashboard.setToolTipText("Click para ir al Panel Principal");
        btn_dashboard.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_dashboard.setOver(true);
        btn_dashboard.setRadius(30);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        btn_inventario.setText("📦 Inventario");
        btn_inventario.setToolTipText("Click para ver Inventario");
        btn_inventario.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_inventario.setOver(true);
        btn_inventario.setRadius(30);
        btn_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventarioActionPerformed(evt);
            }
        });

        btn_solicitudes.setText("📩  Solicitudes");
        btn_solicitudes.setToolTipText("Click para ver Solicitudes (solo administradores)");
        btn_solicitudes.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_solicitudes.setOver(true);
        btn_solicitudes.setRadius(30);
        btn_solicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitudesActionPerformed(evt);
            }
        });

        btn_usuarios.setText("‍👨 Usuarios");
        btn_usuarios.setToolTipText("Click para ver usuarios (solo administradores)");
        btn_usuarios.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_usuarios.setOver(true);
        btn_usuarios.setRadius(30);
        btn_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariosActionPerformed(evt);
            }
        });

        btn_reportes.setText("📋 Reportes");
        btn_reportes.setToolTipText("Click para ver los Reportes (solo administradores)");
        btn_reportes.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_reportes.setOver(true);
        btn_reportes.setRadius(30);
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });

        btn_ayuda.setText("📞Ayuda");
        btn_ayuda.setToolTipText("Click para ir a ayuda");
        btn_ayuda.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_ayuda.setOver(true);
        btn_ayuda.setRadius(30);
        btn_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ayudaActionPerformed(evt);
            }
        });

        lbl_configuracion.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbl_configuracion.setText("⚙️ ️Configuración");
        lbl_configuracion.setToolTipText("Accede a la configuración general");
        lbl_configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_configuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_configuracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_configuracionMouseExited(evt);
            }
        });

        lbl_logout.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbl_logout.setText("📲 Cerrar Sesión");
        lbl_logout.setToolTipText("Cerrar sesión actual");
        lbl_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pan_menuLatIzqLayout = new javax.swing.GroupLayout(pan_menuLatIzq);
        pan_menuLatIzq.setLayout(pan_menuLatIzqLayout);
        pan_menuLatIzqLayout.setHorizontalGroup(
            pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgKintLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_menuLatIzqLayout.createSequentialGroup()
                        .addGroup(pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_solicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pan_menuLatIzqLayout.setVerticalGroup(
            pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(imgKintLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(lbl_configuracion)
                .addGap(18, 18, 18)
                .addComponent(lbl_logout)
                .addContainerGap())
        );

        pan_bg.add(pan_menuLatIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 800));

        pan_cabecera.setBackground(new java.awt.Color(64, 219, 255));
        pan_cabecera.setForeground(new java.awt.Color(99, 101, 105));
        pan_cabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pan_cabeceraMouseDragged(evt);
            }
        });
        pan_cabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pan_cabeceraMousePressed(evt);
            }
        });
        pan_cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_icon.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lbl_icon.setForeground(new java.awt.Color(0, 0, 0));
        lbl_icon.setText("🏠 / ");
        pan_cabecera.add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        lbl_exit.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(0, 0, 0));
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.setToolTipText("Salir");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_exitMousePressed(evt);
            }
        });
        pan_cabecera.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 40, 30));

        lbl_navegador1.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        lbl_navegador1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_navegador1.setText("Usuarios /  Editar usuario");
        pan_cabecera.add(lbl_navegador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 440, 30));

        pan_bg.add(pan_cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 1020, 30));

        jSeparator1.setBackground(new java.awt.Color(184, 184, 184));
        jSeparator1.setForeground(new java.awt.Color(184, 184, 184));
        pan_bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 103, 1420, 10));

        lbl_nameholder.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        pan_bg.add(lbl_nameholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 80, 40));

        lbl_userSVG.setToolTipText("Ver perfil");
        lbl_userSVG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pan_bg.add(lbl_userSVG, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 40, 40, 40));

        lbl_username.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lbl_username.setText("Usuario:");
        pan_bg.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 80, 40));

        lbl_pass.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lbl_pass.setForeground(new java.awt.Color(0, 0, 0));
        lbl_pass.setText("Contraseña");

        lbl_navegador2.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lbl_navegador2.setForeground(new java.awt.Color(0, 0, 0));
        lbl_navegador2.setText("Rol a asignar");

        cb_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador\t", "Supervisor", "Técnico" }));

        lbl_navegador3.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lbl_navegador3.setForeground(new java.awt.Color(0, 0, 0));
        lbl_navegador3.setText("Estado");

        lbl_navegador4.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lbl_navegador4.setForeground(new java.awt.Color(0, 0, 0));
        lbl_navegador4.setText("Nombre");

        btn_generarPass.setText("Generar");
        btn_generarPass.setToolTipText("Click para ver los Reportes (solo administradores)");
        btn_generarPass.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_generarPass.setOver(true);
        btn_generarPass.setRadius(30);
        btn_generarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarPassActionPerformed(evt);
            }
        });

        checkb_activo.setSelected(true);
        checkb_activo.setText("Activo");
        checkb_activo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkb_activoActionPerformed(evt);
            }
        });

        lbl_navegador5.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lbl_navegador5.setForeground(new java.awt.Color(0, 0, 0));
        lbl_navegador5.setText("Correo");

        lbl_navegador6.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lbl_navegador6.setForeground(new java.awt.Color(0, 0, 0));
        lbl_navegador6.setText("Tarea (se puede dejar en blanco)");

        ta_tarea.setColumns(20);
        ta_tarea.setRows(5);
        jScrollPane1.setViewportView(ta_tarea);

        lbl_pass1.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lbl_pass1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_pass1.setText("Fecha de nacimiento");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_navegador6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                            .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(roundedPanel1Layout.createSequentialGroup()
                                    .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_navegador4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbl_navegador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(roundedPanel1Layout.createSequentialGroup()
                                    .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_generarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(roundedPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_navegador3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(checkb_activo))
                                .addComponent(lbl_navegador5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1))
                    .addComponent(dc_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_navegador4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_navegador2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_navegador5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(lbl_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_generarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkb_activo)
                    .addComponent(lbl_navegador3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_navegador6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lbl_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dc_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pan_bg.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 910, 510));

        lbl_titulo.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulo.setText("Registro de Usuario");
        pan_bg.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 210, 30));

        btn_editar.setText("Editar");
        btn_editar.setToolTipText("Click para ir a ayuda");
        btn_editar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_editar.setOver(true);
        btn_editar.setRadius(30);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        pan_bg.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 730, 120, 40));

        getContentPane().add(pan_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void pan_cabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseinX, y - mouseinY);
    }//GEN-LAST:event_pan_cabeceraMouseDragged

    private void pan_cabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMousePressed
        mouseinX = evt.getX();
        mouseinY = evt.getY();
    }//GEN-LAST:event_pan_cabeceraMousePressed

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        if (!requerirRolPorId(1, 2)) {
            return;
        }
        JOptionPane.showMessageDialog(this, "Redirigiendo a gestión de usuarios.");
    }//GEN-LAST:event_btn_reportesActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        this.dispose();
        new DashboardView().setVisible(true);
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventarioActionPerformed
        this.dispose();
        new InventoryView().setVisible(true);
    }//GEN-LAST:event_btn_inventarioActionPerformed

    private void btn_solicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitudesActionPerformed
        if (!requerirRolPorId(1, 2)) {
            return;
        }
        new RequestsView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_solicitudesActionPerformed

    private void btn_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariosActionPerformed
        if (!requerirRolPorId(1)) {
            return;
        }
        this.dispose();
        new UsersView().setVisible(true);
    }//GEN-LAST:event_btn_usuariosActionPerformed

    private void btn_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ayudaActionPerformed

    private void lbl_configuracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_configuracionMouseEntered
        // TODO add your handling code here:
        lbl_configuracion.setForeground(new java.awt.Color(0, 178, 226));

    }//GEN-LAST:event_lbl_configuracionMouseEntered

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:
        int res;
        res = JOptionPane.showConfirmDialog(null, "¿Desea salir? \n", "Salir", JOptionPane.YES_NO_OPTION);
        if (res == 1) {
            return;
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered
        lbl_exit.setForeground(new java.awt.Color(0, 178, 226));
    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited
        lbl_exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbl_exitMouseExited

    private void lbl_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exitMousePressed

    private void lbl_configuracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_configuracionMouseExited
        lbl_configuracion.setForeground(Color.BLACK);

    }//GEN-LAST:event_lbl_configuracionMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lbl_nameholder.setText(nombreUsuario);
        System.out.println(nombreUsuario);
        cargarUsuario();
    }//GEN-LAST:event_formWindowActivated

    private void btn_generarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarPassActionPerformed
        String chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789@#$%";
        StringBuilder sb = new StringBuilder();
        java.util.Random r = new java.util.Random();
        for (int i = 0; i < 10; i++) {
            sb.append(chars.charAt(r.nextInt(chars.length())));
        }
        tf_pass.setText(sb.toString());
    }//GEN-LAST:event_btn_generarPassActionPerformed

    private void checkb_activoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkb_activoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkb_activoActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        onGuardarUsuario();
    }//GEN-LAST:event_btn_editarActionPerformed

    // Autorizacion por ID de rol, la sintaxis de ... hace referencia a un parámetro multivariable, para que pueda poner desde 0...* argumentos
    //útil ya que en lugar de mandar a llamar la función y hacer 3 combinaciones diferentes de arreglos enteros, mejor paso directamente las constantes
    private boolean requerirRolPorId(int... idsPermitidos) {
        if (u == null) {
            JOptionPane.showMessageDialog(this, "Primero inicia sesión.", "Sesión requerida", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        int idRol = u.getIdRol();
        for (int id : idsPermitidos) {
            if (idRol == id) {
                return true;
            }
        }
        JOptionPane.showMessageDialog(this,
                "Solo usuarios autorizados pueden acceder a esta función.\nTu rol: " + u.getRolNombre(),
                "Acceso restringido", JOptionPane.WARNING_MESSAGE);
        return false;
    }

    // ======== Validación del formulario ========
    private boolean validarFormulario() {
        String nombre = t(tf_nombre.getText());
        String correo = t(tf_correo.getText());
        String pass = t(tf_pass.getText());
        String tarea = t(ta_tarea.getText());
        java.util.Date fnac = dc_fechaNacimiento.getDate();

        StringBuilder sb = new StringBuilder();

        if (nombre.isEmpty()) {
            sb.append("• El nombre es obligatorio.\n");
        }
        if (nombre.length() > 120) {
            sb.append("• El nombre no debe exceder 120 caracteres.\n");
        }

        if (correo.isEmpty()) {
            sb.append("• El correo es obligatorio.\n");
        } else if (!correoValido(correo)) {
            sb.append("• El correo no tiene un formato válido.\n");
        }

        if (tarea.length() > 600) {
            sb.append("• La tarea no debe exceder 600 caracteres.\n");
        }

        if (fnac != null) {
            // Evitar fechas futuras
            if (fnac.after(new java.util.Date())) {
                sb.append("• La fecha de nacimiento no puede ser futura.\n");
            }
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Datos incompletos", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    // ======== Construir el Usuario desde la UI ========
    private Usuario buildUsuarioDesdeUI() {
        pck_model.Usuario nuevo = new pck_model.Usuario();

        nuevo.setNombre(t(tf_nombre.getText()));
        nuevo.setCorreo(t(tf_correo.getText()));
        nuevo.setIdRol(rolSeleccionadoId());
        nuevo.setActivo(checkb_activo.isSelected());
        nuevo.setTarea(t(ta_tarea.getText()));

        // Hash de la contraseña para el campo contrasena_hash
        String passPlano = t(tf_pass.getText());
        nuevo.setContrasenaHash(hashSHA256(passPlano));

        // Fecha de nacimiento 
        Date fnac = dc_fechaNacimiento.getDate();
        nuevo.setFechaNacimiento(toSqlDate(fnac));

        return nuevo;
    }

    private void cargarUsuario() {
        try {
            Usuario u = usuarioDAO.findById(idUsuario);
            if (u == null) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró el usuario con ID: " + idUsuario,
                        "Aviso", JOptionPane.WARNING_MESSAGE);
                this.dispose();
                new UsersView().setVisible(true);
                return;
            }

            // Nombre
            tf_nombre.setText(t(u.getNombre()));

            // Correo
            tf_correo.setText(t(u.getCorreo()));

            // Rol
            seleccionarRolEnCombo(u.getIdRol());

            // Activo
            checkb_activo.setSelected(u.isActivo());

            // Tarea 
            ta_tarea.setText(t(u.getTarea()));

            // Fecha de nacimiento 
            if (u.getFechaNacimiento() != null) {
                // java.sql.Date -> convertir a java.util.Date
                java.util.Date d = new java.util.Date(u.getFechaNacimiento().getTime());
                dc_fechaNacimiento.setDate(d);
            } else {
                dc_fechaNacimiento.setDate(null);
            }

            // Contraseña
            tf_pass.setText("");

            lbl_titulo.setText("Editar Usuario (ID " + u.getIdUsuario() + ")");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar el usuario:\n" + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
            new UsersView().setVisible(true);
        }
    }

    // Helper para seleccionar el rol en el combo a partir del id_rol
    private void seleccionarRolEnCombo(int idRol) {
        String etiqueta;
        if (idRol == 1) {
            etiqueta = "Administrador";
        } else if (idRol == 2) {
            etiqueta = "Supervisor";
        } else {
            etiqueta = "Técnico";
        }

        //Busqueda por prefijo
        for (int i = 0; i < cb_rol.getItemCount(); i++) {
            String it = String.valueOf(cb_rol.getItemAt(i));
            if (it != null && it.trim().toUpperCase().startsWith(etiqueta.toUpperCase())) {
                cb_rol.setSelectedIndex(i);
                return;
            }
        }

        // fallback
        if (cb_rol.getItemCount() > 0) {
            cb_rol.setSelectedIndex(0);
        }
    }

    // ======== Guardar ========
    private void onGuardarUsuario() {
        if (!validarFormulario()) {
            return;
        }

        // 1) Validar correo duplicado 
        String correoNuevo = t(tf_correo.getText());
        if (usuarioDAO.existsCorreoForOther(correoNuevo, idUsuario)) {
            JOptionPane.showMessageDialog(this,
                    "El correo ya está utilizado por otro usuario.",
                    "Correo duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2) Construir objeto desde UI 
        Usuario uEdit = buildUsuarioDesdeUI();
        uEdit.setIdUsuario(idUsuario);

        // 3) Actualizar datos generales 
        boolean okUpdate = usuarioDAO.update(uEdit);

        // 4) Si el campo de contraseña tiene algo
        String passPlano = t(tf_pass.getText());
        boolean okPass = true;
        if (!passPlano.isEmpty()) {
            String nuevoHash = hashSHA256(passPlano);
            okPass = usuarioDAO.updatePassword(idUsuario, nuevoHash);
        }

        if (okUpdate && okPass) {
            JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new UsersView().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo actualizar el usuario.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    // ======== Helpers básicos ========
    private String t(String s) {
        return s == null ? "" : s.trim();
    }

    private boolean correoValido(String correo) {
        // Regex correo
        return correo != null && correo.matches("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$");
    }

    private int rolSeleccionadoId() {
        String rolSel = (String) cb_rol.getSelectedItem();
        if (rolSel == null) {
            return 3;
        }
        rolSel = rolSel.trim().toUpperCase();
        if (rolSel.startsWith("ADMIN")) {
            return 1;
        }
        if (rolSel.startsWith("SUPERV")) {
            return 2;
        }
        return 3; // Técnico
    }

    private String hashSHA256(String texto) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hash = md.digest(texto.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder();
            for (byte b : hash) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            return texto;
        }
    }

    private java.sql.Date toSqlDate(java.util.Date d) {
        return (d == null) ? null : new java.sql.Date(d.getTime());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pck_customComponents.CustomButton btn_ayuda;
    private pck_customComponents.CustomButton btn_dashboard;
    private pck_customComponents.CustomButton btn_editar;
    private pck_customComponents.CustomButton btn_generarPass;
    private pck_customComponents.CustomButton btn_inventario;
    private pck_customComponents.CustomButton btn_reportes;
    private pck_customComponents.CustomButton btn_solicitudes;
    private pck_customComponents.CustomButton btn_usuarios;
    private javax.swing.JComboBox<String> cb_rol;
    private javax.swing.JCheckBox checkb_activo;
    private com.toedter.calendar.JDateChooser dc_fechaNacimiento;
    private javax.swing.JLabel imgKintLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_configuracion;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_nameholder;
    private javax.swing.JLabel lbl_navegador1;
    private javax.swing.JLabel lbl_navegador2;
    private javax.swing.JLabel lbl_navegador3;
    private javax.swing.JLabel lbl_navegador4;
    private javax.swing.JLabel lbl_navegador5;
    private javax.swing.JLabel lbl_navegador6;
    private javax.swing.JLabel lbl_pass;
    private javax.swing.JLabel lbl_pass1;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_userSVG;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pan_bg;
    private javax.swing.JPanel pan_cabecera;
    private javax.swing.JPanel pan_menuLatIzq;
    private pck_customComponents.RoundedPanel roundedPanel1;
    private pck_customComponents.RoundedTextArea ta_tarea;
    private pck_customComponents.RoundedTextField tf_correo;
    private pck_customComponents.RoundedTextField tf_nombre;
    private pck_customComponents.RoundedTextField tf_pass;
    // End of variables declaration//GEN-END:variables
}
