package pck_GUIs;

import java.awt.Color;
import static java.awt.Color.WHITE;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import pck_dao.CategoriaDAO;
import pck_dao.ProductoDAO;
import pck_model.Categoria;
import pck_model.Producto;
import pck_model.TipoProducto;
import pck_model.Usuario;
import pck_service.Session;

/**
 *
 * @author dieca
 */
public class EditProductView extends javax.swing.JFrame {

    private int idProducto = 0;
    private final ProductoDAO productoDAO = new ProductoDAO();
    private Producto productoActual = null;
    int mouseinX, mouseinY;
    Rescalar escalar = new Rescalar();
    Usuario u = Session.get();
    String nombreUsuario = u.getNombre();
    String rol = u.getRolNombre();
    int id = u.getIdUsuario();
    LocalDate currentDate = LocalDate.now();

    /**
     * Creates new form login
     */
    public EditProductView(int idProducto) {
        initComponents();
        setLocationRelativeTo(null);
        this.idProducto = idProducto;
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                escalar.escalarLabel(imgKintLogo, "/pck_img/kintLogo.png");
                escalar.escalarLabel(lbl_userSVG, "/pck_img/avatarIcon.png");
            }
        });

        java.awt.event.ComponentAdapter resizeListener = new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                if (e.getComponent() == imgKintLogo) {
                    escalar.escalarLabel(imgKintLogo, "/pck_img/kintLogo.png");
                } else if (e.getComponent() == lbl_userSVG) {
                    escalar.escalarLabel(lbl_userSVG, "/pck_img/avatarIcon.png");
                }
            }
        };
        imgKintLogo.addComponentListener(resizeListener);
        lbl_userSVG.addComponentListener(resizeListener);

        setIconImage(new ImageIcon(getClass().getResource("/pck_img/favicon.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_bg = new javax.swing.JPanel();
        pan_menuLatIzq = new javax.swing.JPanel();
        imgKintLogo = new javax.swing.JLabel();
        btn_dashboard = new pck_customComponents.CustomButton();
        btn_inventario = new pck_customComponents.CustomButton();
        btn_solicitudes = new pck_customComponents.CustomButton();
        btn_usuarios = new pck_customComponents.CustomButton();
        btn_reportes = new pck_customComponents.CustomButton();
        btn_ayuda = new pck_customComponents.CustomButton();
        lbl_configuracion = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        pan_cabecera = new javax.swing.JPanel();
        lbl_navegador = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_nameholder = new javax.swing.JLabel();
        lbl_userSVG = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        roundedPanel1 = new pck_customComponents.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_nombreProducto = new pck_customComponents.RoundedTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_sku = new pck_customComponents.RoundedTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcion = new pck_customComponents.RoundedTextArea();
        jLabel4 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cb_categoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cb_unidades = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tf_codigoBarras = new pck_customComponents.RoundedTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_ubicación = new pck_customComponents.RoundedTextField();
        jLabel9 = new javax.swing.JLabel();
        spn_cantidad = new javax.swing.JSpinner();
        roundedPanel2 = new pck_customComponents.RoundedPanel();
        lbl_imagen = new javax.swing.JLabel();
        btn_subirFoto = new pck_customComponents.CustomButton();
        lbl_username1 = new javax.swing.JLabel();
        btn_editar = new pck_customComponents.CustomButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KINT - Dashboard");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_bg.setBackground(new java.awt.Color(245, 245, 245));
        pan_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_menuLatIzq.setBackground(new java.awt.Color(255, 255, 255));

        imgKintLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btn_dashboard.setText("📰 Dashboard");
        btn_dashboard.setToolTipText("Click para ir al Panel Principal");
        btn_dashboard.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_dashboard.setOver(true);
        btn_dashboard.setRadius(30);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        btn_inventario.setText("📦 Inventario");
        btn_inventario.setToolTipText("Click para ver Inventario");
        btn_inventario.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_inventario.setOver(true);
        btn_inventario.setRadius(30);
        btn_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventarioActionPerformed(evt);
            }
        });

        btn_solicitudes.setText("📩  Solicitudes");
        btn_solicitudes.setToolTipText("Click para ver Solicitudes (solo administradores)");
        btn_solicitudes.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_solicitudes.setOver(true);
        btn_solicitudes.setRadius(30);
        btn_solicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitudesActionPerformed(evt);
            }
        });

        btn_usuarios.setText("‍👨 Usuarios");
        btn_usuarios.setToolTipText("Click para ver usuarios (solo administradores)");
        btn_usuarios.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_usuarios.setOver(true);
        btn_usuarios.setRadius(30);
        btn_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariosActionPerformed(evt);
            }
        });

        btn_reportes.setText("📋 Reportes");
        btn_reportes.setToolTipText("Click para ver los Reportes (solo administradores)");
        btn_reportes.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_reportes.setOver(true);
        btn_reportes.setRadius(30);
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });

        btn_ayuda.setText("📞Ayuda");
        btn_ayuda.setToolTipText("Click para ir a ayuda");
        btn_ayuda.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_ayuda.setOver(true);
        btn_ayuda.setRadius(30);
        btn_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ayudaActionPerformed(evt);
            }
        });

        lbl_configuracion.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbl_configuracion.setText("⚙️ ️Configuración");
        lbl_configuracion.setToolTipText("Accede a la configuración general");
        lbl_configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_configuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_configuracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_configuracionMouseExited(evt);
            }
        });

        lbl_logout.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbl_logout.setText("📲 Cerrar Sesión");
        lbl_logout.setToolTipText("Cerrar sesión actual");
        lbl_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pan_menuLatIzqLayout = new javax.swing.GroupLayout(pan_menuLatIzq);
        pan_menuLatIzq.setLayout(pan_menuLatIzqLayout);
        pan_menuLatIzqLayout.setHorizontalGroup(
            pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgKintLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_menuLatIzqLayout.createSequentialGroup()
                        .addGroup(pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_solicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pan_menuLatIzqLayout.setVerticalGroup(
            pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(imgKintLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(lbl_configuracion)
                .addGap(18, 18, 18)
                .addComponent(lbl_logout)
                .addContainerGap())
        );

        pan_bg.add(pan_menuLatIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 800));

        pan_cabecera.setBackground(new java.awt.Color(64, 219, 255));
        pan_cabecera.setForeground(new java.awt.Color(99, 101, 105));
        pan_cabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pan_cabeceraMouseDragged(evt);
            }
        });
        pan_cabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pan_cabeceraMousePressed(evt);
            }
        });
        pan_cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_navegador.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        lbl_navegador.setForeground(new java.awt.Color(0, 0, 0));
        lbl_navegador.setText("Inventario  / Editar Producto");
        pan_cabecera.add(lbl_navegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 440, 30));

        lbl_icon.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lbl_icon.setForeground(new java.awt.Color(0, 0, 0));
        lbl_icon.setText("🏠 / ");
        pan_cabecera.add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        lbl_exit.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(0, 0, 0));
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.setToolTipText("Salir");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_exitMousePressed(evt);
            }
        });
        pan_cabecera.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 40, 30));

        pan_bg.add(pan_cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 1020, 30));

        jSeparator1.setBackground(new java.awt.Color(184, 184, 184));
        jSeparator1.setForeground(new java.awt.Color(184, 184, 184));
        pan_bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 103, 1420, 10));

        lbl_nameholder.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        pan_bg.add(lbl_nameholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 80, 40));

        lbl_userSVG.setToolTipText("Ver perfil");
        lbl_userSVG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pan_bg.add(lbl_userSVG, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 40, 40, 40));

        lbl_title.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title.setText("Formulario de edición");
        pan_bg.add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 240, 40));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre del producto");

        tf_nombreProducto.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tf_nombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreProductoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SKU");

        tf_sku.setEnabled(false);
        tf_sku.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tf_sku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_skuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Descripción (<500 caracteres)");

        ta_descripcion.setColumns(20);
        ta_descripcion.setRows(5);
        ta_descripcion.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(ta_descripcion);

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo");

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATERIAL", "HERRAMIENTA", "DISPOSITIVO" }));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Categoría");

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Unidad de Medida");

        cb_unidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIEZA", "KILOS", "GRAMOS", "LITROS", "MILILITROS", "UNIDADES", "METROS", "CENTÍMETROS", "CAJAS", "PALLETS", "DOCENA", "KIT", "PAQUETE" }));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Código de Barras");

        tf_codigoBarras.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tf_codigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoBarrasActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ubicación física");

        tf_ubicación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ubicaciónActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Stock");

        spn_cantidad.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        spn_cantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_sku, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(tf_codigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                            .addComponent(tf_ubicación, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(spn_cantidad))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roundedPanel1Layout.createSequentialGroup()
                            .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(roundedPanel1Layout.createSequentialGroup()
                                    .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel6)
                                .addComponent(cb_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_sku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_codigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ubicación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spn_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pan_bg.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 590, 580));

        lbl_imagen.setText("jLabel10");

        btn_subirFoto.setText("Subir Foto");
        btn_subirFoto.setToolTipText("Click para ir al Panel Principal");
        btn_subirFoto.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_subirFoto.setOver(true);
        btn_subirFoto.setRadius(30);
        btn_subirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subirFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btn_subirFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_subirFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pan_bg.add(roundedPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 370, 580));

        lbl_username1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lbl_username1.setText("Usuario:");
        pan_bg.add(lbl_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 80, 40));

        btn_editar.setText("Editar Producto");
        btn_editar.setToolTipText("Click para ir al Panel Principal");
        btn_editar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_editar.setOver(true);
        btn_editar.setRadius(30);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        pan_bg.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 120, 140, 40));

        getContentPane().add(pan_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void pan_cabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseinX, y - mouseinY);
    }//GEN-LAST:event_pan_cabeceraMouseDragged

    private void pan_cabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMousePressed
        mouseinX = evt.getX();
        mouseinY = evt.getY();
    }//GEN-LAST:event_pan_cabeceraMousePressed

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        if (!requerirRolPorId(1, 2)) {
            return;
        }
        JOptionPane.showMessageDialog(this, "Redirigiendo a gestión de usuarios.");
    }//GEN-LAST:event_btn_reportesActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        new DashboardView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventarioActionPerformed
        new InventoryView().setVisible(true);
        this.dispose();    }//GEN-LAST:event_btn_inventarioActionPerformed

    private void btn_solicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitudesActionPerformed
        if (!requerirRolPorId(1, 2)) {
            return;
        }
        JOptionPane.showMessageDialog(this, "Redirigiendo a gestión de usuarios.");
    }//GEN-LAST:event_btn_solicitudesActionPerformed

    private void btn_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariosActionPerformed
        if (!requerirRolPorId(1)) {
            return;
        }
        JOptionPane.showMessageDialog(this, "Redirigiendo a gestión de usuarios.");
    }//GEN-LAST:event_btn_usuariosActionPerformed

    private void btn_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ayudaActionPerformed

    private void lbl_configuracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_configuracionMouseEntered
        // TODO add your handling code here:
        lbl_configuracion.setForeground(new java.awt.Color(0, 178, 226));

    }//GEN-LAST:event_lbl_configuracionMouseEntered

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:
        int res;
        res = JOptionPane.showConfirmDialog(null, "¿Desea salir? \n", "Salir", JOptionPane.YES_NO_OPTION);
        if (res == 1) {
            return;
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered
        lbl_exit.setForeground(new java.awt.Color(0, 178, 226));
    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited
        lbl_exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbl_exitMouseExited

    private void lbl_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exitMousePressed

    private void lbl_configuracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_configuracionMouseExited
        lbl_configuracion.setForeground(Color.BLACK);

    }//GEN-LAST:event_lbl_configuracionMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lbl_nameholder.setText(nombreUsuario);
        System.out.println(nombreUsuario);
        cargarCategorias();
        cargarProducto();
    }//GEN-LAST:event_formWindowActivated

    private void btn_subirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subirFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_subirFotoActionPerformed

    private void tf_nombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreProductoActionPerformed

    private void tf_skuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_skuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_skuActionPerformed

    private void tf_codigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_codigoBarrasActionPerformed

    private void tf_ubicaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ubicaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ubicaciónActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        onGuardarCambios();
    }//GEN-LAST:event_btn_editarActionPerformed

    // Autorizacion por ID de rol, la sintaxis de ... hace referencia a un parámetro multivariable, para que pueda poner desde 0...* argumentos
    //útil ya que en lugar de mandar a llamar la función y hacer 3 combinaciones diferentes de arreglos enteros, mejor paso directamente las constantes
    private boolean requerirRolPorId(int... idsPermitidos) {
        if (u == null) {
            JOptionPane.showMessageDialog(this, "Primero inicia sesión.", "Sesión requerida", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        int idRol = u.getIdRol();
        for (int id : idsPermitidos) {
            if (idRol == id) {
                return true;
            }
        }
        JOptionPane.showMessageDialog(this,
                "Solo usuarios autorizados pueden acceder a esta función.\nTu rol: " + u.getRolNombre(),
                "Acceso restringido", JOptionPane.WARNING_MESSAGE);
        return false;
    }

    private void cargarCategorias() {
        CategoriaDAO dao = new CategoriaDAO();
        List<Categoria> cats = dao.findAll();

        DefaultComboBoxModel<Categoria> model = new DefaultComboBoxModel<>();
        //placeholder
        model.addElement(new Categoria(0, "— Selecciona categoría —", ""));

        for (Categoria c : cats) {
            model.addElement(c);
        }
        cb_categoria.setModel(model);
    }

    // Helpers
    private String t(String s) {
        return s == null ? "" : s.trim();
    }

    private TipoProducto parseTipo(String s) {
        try {
            return s == null ? null : TipoProducto.valueOf(s.trim());
        } catch (IllegalArgumentException ex) {
            return null;
        }
    }

    private boolean validarFormulario() {
        String nombre = t(tf_nombreProducto.getText());
        String sku = t(tf_sku.getText());
        String desc = t(ta_descripcion.getText());
        String tipoStr = (cb_tipo.getSelectedItem() == null) ? "" : cb_tipo.getSelectedItem().toString();
        TipoProducto tipo = parseTipo(tipoStr);
        Categoria cat = (Categoria) cb_categoria.getSelectedItem();
        String uMedida = (cb_unidades.getSelectedItem() == null) ? "" : cb_unidades.getSelectedItem().toString();
        String ubic = t(tf_ubicación.getText());
        String codBarras = t(tf_codigoBarras.getText());

        StringBuilder sb = new StringBuilder();

        if (nombre.isEmpty()) {
            sb.append("• El nombre es obligatorio.\n");
        }
        if (sku.isEmpty()) {
            sb.append("• El SKU es obligatorio.\n");
        }
        if (tipo == null) {
            sb.append("• Selecciona un tipo de producto.\n");
        }
        if (cat == null || cat.getIdCategoria() <= 0) {
            sb.append("• Selecciona una categoría válida.\n");
        }
        if (uMedida.isEmpty()) {
            sb.append("• Selecciona la unidad de medida.\n");
        }

        if (nombre.length() > 120) {
            sb.append("• El nombre no debe exceder 120 caracteres.\n");
        }
        if (sku.length() > 60) {
            sb.append("• El SKU no debe exceder 60 caracteres.\n");
        }
        if (desc.length() > 500) {
            sb.append("• La descripción no debe exceder 500 caracteres.\n");
        }
        if (codBarras.length() > 80) {
            sb.append("• El código de barras no debe exceder 80 caracteres.\n");
        }
        if (ubic.length() > 120) {
            sb.append("• La ubicación no debe exceder 120 caracteres.\n");
        }

        Number n = (Number) spn_cantidad.getValue();
        int stock = (n == null) ? 0 : n.intValue();
        if (stock < 0) {
            sb.append("• La cantidad no puede ser negativa.\n");
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Datos incompletos", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private Producto buildProductoDesdeUI() {
        Producto p = new Producto();

        p.setNombre(t(tf_nombreProducto.getText()));
        p.setSku(t(tf_sku.getText()));
        p.setDescripcion(t(ta_descripcion.getText()));

        String tipoStr = (cb_tipo.getSelectedItem() == null) ? "" : cb_tipo.getSelectedItem().toString();
        p.setTipo(parseTipo(tipoStr));

        Categoria cat = (Categoria) cb_categoria.getSelectedItem();
        p.setIdCategoria(cat != null ? cat.getIdCategoria() : 0);

        p.setuMedida((cb_unidades.getSelectedItem() == null) ? "" : cb_unidades.getSelectedItem().toString());
        p.setCodigoBarras(t(tf_codigoBarras.getText()));
        p.setUbicacion(t(tf_ubicación.getText()));

        Number n = (Number) spn_cantidad.getValue();
        p.setStock(n == null ? 0 : n.intValue());

        p.setActivo(true);   // Activo al crear
        return p;
    }

    private void onGuardarCambios() {
        if (!validarFormulario()) {
            return;
        }

        Producto p = buildProductoParaActualizar();
        try {
            boolean ok = productoDAO.update(p);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Producto actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                new InventoryView().setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el producto.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al actualizar:\n" + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarFormulario() {
        tf_nombreProducto.setText("");
        tf_sku.setText("");
        ta_descripcion.setText("");
        cb_tipo.setSelectedIndex(-1);
        cb_categoria.setSelectedIndex(0);
        cb_unidades.setSelectedIndex(-1);
        tf_codigoBarras.setText("");
        tf_ubicación.setText("");
        spn_cantidad.setValue(0);
    }

    private void cargarProducto() {
        try {
            productoActual = productoDAO.findById(idProducto);
            if (productoActual == null) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró el producto con ID: " + idProducto,
                        "Aviso", JOptionPane.WARNING_MESSAGE);
                // Regresar al inventario
                new InventoryView().setVisible(true);
                dispose();
                return;
            }

            // Título y SKU (lo tienes deshabilitado en el diseñador)
            lbl_title.setText("Editar producto (ID " + idProducto + ")");
            tf_sku.setText(productoActual.getSku());

            // Texto
            tf_nombreProducto.setText(n(productoActual.getNombre()));
            ta_descripcion.setText(n(productoActual.getDescripcion()));
            tf_codigoBarras.setText(n(productoActual.getCodigoBarras()));
            tf_ubicación.setText(n(productoActual.getUbicacion()));

            // Tipo (según enum)
            if (productoActual.getTipo() != null) {
                cb_tipo.setSelectedItem(productoActual.getTipo().name());
            } else {
                cb_tipo.setSelectedIndex(-1);
            }

            // Categoría: seleccionar por id
            seleccionarCategoriaEnCombo(productoActual.getIdCategoria());

            // U. Medida
            if (productoActual.getuMedida() != null) {
                cb_unidades.setSelectedItem(productoActual.getuMedida());
            } else {
                cb_unidades.setSelectedIndex(-1);
            }

            // Stock
            spn_cantidad.setValue(productoActual.getStock());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar el producto:\n" + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String n(String s) {
        return s == null ? "" : s;
    }

    private void seleccionarCategoriaEnCombo(int idCategoria) {
        if (cb_categoria.getItemCount() == 0) {
            return;
        }

        for (int i = 0; i < cb_categoria.getItemCount(); i++) {
            Categoria c = cb_categoria.getItemAt(i);
            if (c != null && c.getIdCategoria() == idCategoria) {
                cb_categoria.setSelectedIndex(i);
                return;
            }
        }
        // Si no se encontró, deja en placeholder (normalmente índice 0)
        cb_categoria.setSelectedIndex(0);
    }

    private Producto buildProductoParaActualizar() {
        Producto p = buildProductoDesdeUI();
        p.setIdProducto(idProducto);                 // <- importante
        // Mantén campos que no editas si es necesario (activo true/false, etc.)
        p.setActivo(productoActual != null ? productoActual.isActivo() : true);
        return p;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pck_customComponents.CustomButton btn_ayuda;
    private pck_customComponents.CustomButton btn_dashboard;
    private pck_customComponents.CustomButton btn_editar;
    private pck_customComponents.CustomButton btn_inventario;
    private pck_customComponents.CustomButton btn_reportes;
    private pck_customComponents.CustomButton btn_solicitudes;
    private pck_customComponents.CustomButton btn_subirFoto;
    private pck_customComponents.CustomButton btn_usuarios;
    private javax.swing.JComboBox<Categoria> cb_categoria;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JComboBox<String> cb_unidades;
    private javax.swing.JLabel imgKintLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_configuracion;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_imagen;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_nameholder;
    private javax.swing.JLabel lbl_navegador;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_userSVG;
    private javax.swing.JLabel lbl_username1;
    private javax.swing.JPanel pan_bg;
    private javax.swing.JPanel pan_cabecera;
    private javax.swing.JPanel pan_menuLatIzq;
    private pck_customComponents.RoundedPanel roundedPanel1;
    private pck_customComponents.RoundedPanel roundedPanel2;
    private javax.swing.JSpinner spn_cantidad;
    private pck_customComponents.RoundedTextArea ta_descripcion;
    private pck_customComponents.RoundedTextField tf_codigoBarras;
    private pck_customComponents.RoundedTextField tf_nombreProducto;
    private pck_customComponents.RoundedTextField tf_sku;
    private pck_customComponents.RoundedTextField tf_ubicación;
    // End of variables declaration//GEN-END:variables
}
