package pck_GUIs;

import java.awt.Color;
import static java.awt.Color.WHITE;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import pck_dao.CategoriaDAO;
import pck_model.Categoria;
import pck_model.Usuario;
import pck_service.Session;

/**
 *
 * @author dieca
 */
public class EditCategoryView extends javax.swing.JFrame {

    int mouseinX, mouseinY;
    private Rescalar escalar = new Rescalar();
    private Usuario u = Session.get();
    private String nombreUsuario = u.getNombre();
    private int idCategoria;
    private LocalDate currentDate = LocalDate.now();
    private final CategoriaDAO categoriaDAO = new CategoriaDAO();
    private Categoria categoriaActual = null;

    /**
     * Creates new form login
     */
    public EditCategoryView(int idCategoria) {
        initComponents();
        this.idCategoria = idCategoria;
        setLocationRelativeTo(null);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                escalar.escalarLabel(imgKintLogo, "/pck_img/kintLogo.png");
                escalar.escalarLabel(lbl_userSVG, "/pck_img/avatarIcon.png");
            }
        });

        java.awt.event.ComponentAdapter resizeListener = new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                if (e.getComponent() == imgKintLogo) {
                    escalar.escalarLabel(imgKintLogo, "/pck_img/kintLogo.png");
                } else if (e.getComponent() == lbl_userSVG) {
                    escalar.escalarLabel(lbl_userSVG, "/pck_img/avatarIcon.png");
                }
            }
        };
        imgKintLogo.addComponentListener(resizeListener);
        lbl_userSVG.addComponentListener(resizeListener);

        setIconImage(new ImageIcon(getClass().getResource("/pck_img/favicon.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_bg = new javax.swing.JPanel();
        pan_menuLatIzq = new javax.swing.JPanel();
        imgKintLogo = new javax.swing.JLabel();
        btn_dashboard = new pck_customComponents.CustomButton();
        btn_inventario = new pck_customComponents.CustomButton();
        btn_solicitudes = new pck_customComponents.CustomButton();
        btn_usuarios = new pck_customComponents.CustomButton();
        btn_reportes = new pck_customComponents.CustomButton();
        btn_ayuda = new pck_customComponents.CustomButton();
        lbl_configuracion = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        pan_cabecera = new javax.swing.JPanel();
        lbl_icon = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        lbl_navegador1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_nameholder = new javax.swing.JLabel();
        lbl_userSVG = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        roundedPanel1 = new pck_customComponents.RoundedPanel();
        lbl_navegador = new javax.swing.JLabel();
        lbl_navegador3 = new javax.swing.JLabel();
        tf_nombre = new pck_customComponents.RoundedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcion = new pck_customComponents.RoundedTextArea();
        lbl_titulo = new javax.swing.JLabel();
        btn_editar = new pck_customComponents.CustomButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KINT - Dashboard");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_bg.setBackground(new java.awt.Color(245, 245, 245));
        pan_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_menuLatIzq.setBackground(new java.awt.Color(255, 255, 255));

        imgKintLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btn_dashboard.setText("📰 Dashboard");
        btn_dashboard.setToolTipText("Click para ir al Panel Principal");
        btn_dashboard.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_dashboard.setOver(true);
        btn_dashboard.setRadius(30);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        btn_inventario.setText("📦 Inventario");
        btn_inventario.setToolTipText("Click para ver Inventario");
        btn_inventario.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_inventario.setOver(true);
        btn_inventario.setRadius(30);
        btn_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventarioActionPerformed(evt);
            }
        });

        btn_solicitudes.setText("📩  Solicitudes");
        btn_solicitudes.setToolTipText("Click para ver Solicitudes (solo administradores)");
        btn_solicitudes.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_solicitudes.setOver(true);
        btn_solicitudes.setRadius(30);
        btn_solicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitudesActionPerformed(evt);
            }
        });

        btn_usuarios.setText("‍👨 Usuarios");
        btn_usuarios.setToolTipText("Click para ver usuarios (solo administradores)");
        btn_usuarios.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_usuarios.setOver(true);
        btn_usuarios.setRadius(30);
        btn_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariosActionPerformed(evt);
            }
        });

        btn_reportes.setText("📋 Reportes");
        btn_reportes.setToolTipText("Click para ver los Reportes (solo administradores)");
        btn_reportes.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_reportes.setOver(true);
        btn_reportes.setRadius(30);
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });

        btn_ayuda.setText("📞Ayuda");
        btn_ayuda.setToolTipText("Click para ir a ayuda");
        btn_ayuda.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_ayuda.setOver(true);
        btn_ayuda.setRadius(30);
        btn_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ayudaActionPerformed(evt);
            }
        });

        lbl_configuracion.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbl_configuracion.setText("⚙️ ️Configuración");
        lbl_configuracion.setToolTipText("Accede a la configuración general");
        lbl_configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_configuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_configuracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_configuracionMouseExited(evt);
            }
        });

        lbl_logout.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbl_logout.setText("📲 Cerrar Sesión");
        lbl_logout.setToolTipText("Cerrar sesión actual");
        lbl_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pan_menuLatIzqLayout = new javax.swing.GroupLayout(pan_menuLatIzq);
        pan_menuLatIzq.setLayout(pan_menuLatIzqLayout);
        pan_menuLatIzqLayout.setHorizontalGroup(
            pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgKintLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_menuLatIzqLayout.createSequentialGroup()
                        .addGroup(pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_solicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pan_menuLatIzqLayout.setVerticalGroup(
            pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(imgKintLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(lbl_configuracion)
                .addGap(18, 18, 18)
                .addComponent(lbl_logout)
                .addContainerGap())
        );

        pan_bg.add(pan_menuLatIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 800));

        pan_cabecera.setBackground(new java.awt.Color(64, 219, 255));
        pan_cabecera.setForeground(new java.awt.Color(99, 101, 105));
        pan_cabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pan_cabeceraMouseDragged(evt);
            }
        });
        pan_cabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pan_cabeceraMousePressed(evt);
            }
        });
        pan_cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_icon.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lbl_icon.setForeground(new java.awt.Color(0, 0, 0));
        lbl_icon.setText("🏠 / ");
        pan_cabecera.add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        lbl_exit.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(0, 0, 0));
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.setToolTipText("Salir");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_exitMousePressed(evt);
            }
        });
        pan_cabecera.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 40, 30));

        lbl_navegador1.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        lbl_navegador1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_navegador1.setText("Inventario  /  Categorías /  Editar categoría");
        pan_cabecera.add(lbl_navegador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 440, 30));

        pan_bg.add(pan_cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 1020, 30));

        jSeparator1.setBackground(new java.awt.Color(184, 184, 184));
        jSeparator1.setForeground(new java.awt.Color(184, 184, 184));
        pan_bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 103, 1420, 10));

        lbl_nameholder.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        pan_bg.add(lbl_nameholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 80, 40));

        lbl_userSVG.setToolTipText("Ver perfil");
        lbl_userSVG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pan_bg.add(lbl_userSVG, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 40, 40, 40));

        lbl_username.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lbl_username.setText("Usuario:");
        pan_bg.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 80, 40));

        lbl_navegador.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lbl_navegador.setForeground(new java.awt.Color(0, 0, 0));
        lbl_navegador.setText("Nombre de la categoría");

        lbl_navegador3.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lbl_navegador3.setForeground(new java.awt.Color(0, 0, 0));
        lbl_navegador3.setText("Descripción de la categoría");

        ta_descripcion.setColumns(20);
        ta_descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_descripcion);

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_navegador, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_navegador3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_navegador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_navegador3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pan_bg.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 910, 270));

        lbl_titulo.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulo.setText("Edición de categoría");
        pan_bg.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 210, 30));

        btn_editar.setText("Editar");
        btn_editar.setToolTipText("Click para ir al Panel Principal");
        btn_editar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_editar.setOver(true);
        btn_editar.setRadius(30);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        pan_bg.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 90, 40));

        getContentPane().add(pan_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void pan_cabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseinX, y - mouseinY);
    }//GEN-LAST:event_pan_cabeceraMouseDragged

    private void pan_cabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMousePressed
        mouseinX = evt.getX();
        mouseinY = evt.getY();
    }//GEN-LAST:event_pan_cabeceraMousePressed

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        if (!requerirRolPorId(1, 2)) {
            return;
        }
        JOptionPane.showMessageDialog(this, "Redirigiendo a gestión de usuarios.");
    }//GEN-LAST:event_btn_reportesActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        this.dispose();
        new DashboardView().setVisible(true);
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventarioActionPerformed
        this.dispose();
        new InventoryView().setVisible(true);
    }//GEN-LAST:event_btn_inventarioActionPerformed

    private void btn_solicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitudesActionPerformed
        if (!requerirRolPorId(1, 2)) {
            return;
        }
        new RequestsView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_solicitudesActionPerformed

    private void btn_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariosActionPerformed
        if (!requerirRolPorId(1)) {
            return;
        }
        this.dispose();
        new UsersView().setVisible(true);
    }//GEN-LAST:event_btn_usuariosActionPerformed

    private void btn_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ayudaActionPerformed

    private void lbl_configuracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_configuracionMouseEntered
        // TODO add your handling code here:
        lbl_configuracion.setForeground(new java.awt.Color(0, 178, 226));

    }//GEN-LAST:event_lbl_configuracionMouseEntered

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:
        int res;
        res = JOptionPane.showConfirmDialog(null, "¿Desea salir? \n", "Salir", JOptionPane.YES_NO_OPTION);
        if (res == 1) {
            return;
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered
        lbl_exit.setForeground(new java.awt.Color(0, 178, 226));
    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited
        lbl_exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbl_exitMouseExited

    private void lbl_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exitMousePressed

    private void lbl_configuracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_configuracionMouseExited
        lbl_configuracion.setForeground(Color.BLACK);

    }//GEN-LAST:event_lbl_configuracionMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lbl_nameholder.setText(nombreUsuario);
        System.out.println(nombreUsuario);
        cargarCategoria();
    }//GEN-LAST:event_formWindowActivated

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        onGuardarCambios();
    }//GEN-LAST:event_btn_editarActionPerformed

    // Autorizacion por ID de rol, la sintaxis de ... hace referencia a un parámetro multivariable, para que pueda poner desde 0...* argumentos
    //útil ya que en lugar de mandar a llamar la función y hacer 3 combinaciones diferentes de arreglos enteros, mejor paso directamente las constantes
    private boolean requerirRolPorId(int... idsPermitidos) {
        if (u == null) {
            JOptionPane.showMessageDialog(this, "Primero inicia sesión.", "Sesión requerida", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        int idRol = u.getIdRol();
        for (int id : idsPermitidos) {
            if (idRol == id) {
                return true;
            }
        }
        JOptionPane.showMessageDialog(this,
                "Solo usuarios autorizados pueden acceder a esta función.\nTu rol: " + u.getRolNombre(),
                "Acceso restringido", JOptionPane.WARNING_MESSAGE);
        return false;
    }

    private boolean validarFormulario() {
        String nombre = t(tf_nombre.getText());
        String desc = t(ta_descripcion.getText());
        StringBuilder sb = new StringBuilder();

        if (nombre.isEmpty()) {
            sb.append("• El nombre es obligatorio.\n");
        }

        if (nombre.length() > 120) {
            sb.append("• El nombre no debe exceder 120 caracteres.\n");
        }

        if (desc.isEmpty()) {
            sb.append("• La descripción es obligatoria.\n");
        }

        if (nombre.length() > 600) {
            sb.append("• La descripción no debe exceder 600 caracteres.\n");
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Datos incompletos", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private Categoria buildCategoriaDesdeUI() {
        Categoria c = new Categoria();

        c.setNombre(t(tf_nombre.getText()));
        c.setDescripcion(t(ta_descripcion.getText()));
        return c;
    }

    private void limpiarFormulario() {
        tf_nombre.setText("");
        ta_descripcion.setText("");
    }

    private void cargarCategoria() {
        try {
            CategoriaDAO dao = new CategoriaDAO();
            Categoria c = dao.findById(idCategoria); // ajusta al nombre real si difiere
            if (c == null) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró la categoría con ID: " + idCategoria,
                        "Aviso", JOptionPane.WARNING_MESSAGE);
                this.dispose();
                new CategoriesView().setVisible(true);
                return;
            }
            tf_nombre.setText(t(c.getNombre()));
            ta_descripcion.setText(t(c.getDescripcion()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar la categoría:\n" + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
            new CategoriesView().setVisible(true);
        }
    }

    private void onGuardarCambios() {
        if (!validarFormulario()) {
            return;
        }

        Categoria c = buildCategoriaParaActualizar();
        try {
            boolean ok = categoriaDAO.update(c);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Producto actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                new CategoriesView().setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el producto.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al actualizar:\n" + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Categoria buildCategoriaParaActualizar() {
        Categoria c = buildCategoriaDesdeUI();
        c.setIdCategoria(idCategoria);
        return c;
    }

    private String t(String s) {
        return s == null ? "" : s.trim();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pck_customComponents.CustomButton btn_ayuda;
    private pck_customComponents.CustomButton btn_dashboard;
    private pck_customComponents.CustomButton btn_editar;
    private pck_customComponents.CustomButton btn_inventario;
    private pck_customComponents.CustomButton btn_reportes;
    private pck_customComponents.CustomButton btn_solicitudes;
    private pck_customComponents.CustomButton btn_usuarios;
    private javax.swing.JLabel imgKintLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_configuracion;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_nameholder;
    private javax.swing.JLabel lbl_navegador;
    private javax.swing.JLabel lbl_navegador1;
    private javax.swing.JLabel lbl_navegador3;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_userSVG;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pan_bg;
    private javax.swing.JPanel pan_cabecera;
    private javax.swing.JPanel pan_menuLatIzq;
    private pck_customComponents.RoundedPanel roundedPanel1;
    private pck_customComponents.RoundedTextArea ta_descripcion;
    private pck_customComponents.RoundedTextField tf_nombre;
    // End of variables declaration//GEN-END:variables
}
