package pck_GUIs;

import java.awt.Color;
import static java.awt.Color.WHITE;
import java.awt.Component;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import pck_customComponents.AccionesEditor;
import pck_customComponents.AccionesHandler;
import pck_customComponents.AccionesRenderer;
import pck_dao.ProductoDAO;
import pck_model.ProductoRow;
import pck_model.Usuario;
import pck_service.Session;

/**
 *
 * @author dieca
 */
public class InventoryView extends javax.swing.JFrame {

    private static final int UMBRAL_BAJO_STOCK = 1;
    int mouseinX, mouseinY;
    Rescalar escalar = new Rescalar();
    Usuario u = Session.get();
    String nombreUsuario = u.getNombre();
    String tarea = u.getTarea();
    String correo = u.getCorreo();
    String rol = u.getRolNombre();
    int id = u.getIdUsuario();
    LocalDate currentDate = LocalDate.now();

    /**
     * Creates new form login
     */
    public InventoryView() {
        initComponents();
        setLocationRelativeTo(null);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                escalar.escalarLabel(imgKintLogo, "/pck_img/kintLogo.png");
                escalar.escalarLabel(lbl_userSVG, "/pck_img/avatarIcon.png");
            }
        });

        java.awt.event.ComponentAdapter resizeListener = new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                if (e.getComponent() == imgKintLogo) {
                    escalar.escalarLabel(imgKintLogo, "/pck_img/kintLogo.png");
                } else if (e.getComponent() == lbl_userSVG) {
                    escalar.escalarLabel(lbl_userSVG, "/pck_img/avatarIcon.png");
                }
            }
        };
        imgKintLogo.addComponentListener(resizeListener);
        lbl_userSVG.addComponentListener(resizeListener);

        setIconImage(new ImageIcon(getClass().getResource("/pck_img/favicon.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_bg = new javax.swing.JPanel();
        pan_menuLatIzq = new javax.swing.JPanel();
        imgKintLogo = new javax.swing.JLabel();
        btn_dashboard = new pck_customComponents.CustomButton();
        btn_inventario = new pck_customComponents.CustomButton();
        btn_solicitudes = new pck_customComponents.CustomButton();
        btn_usuarios = new pck_customComponents.CustomButton();
        btn_reportes = new pck_customComponents.CustomButton();
        btn_ayuda = new pck_customComponents.CustomButton();
        lbl_configuracion = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        pan_cabecera = new javax.swing.JPanel();
        lbl_navegador = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        lbl_icon1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_nameholder = new javax.swing.JLabel();
        lbl_userSVG = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        pan_resumen = new pck_customComponents.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_agotados = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_stockBajo = new javax.swing.JLabel();
        panel_productos = new pck_customComponents.RoundedPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_productos = new javax.swing.JTable();
        pan_filtroPorTipo = new pck_customComponents.RoundedPanel();
        jLabel7 = new javax.swing.JLabel();
        cb_filtroTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btn_nuevaCategoria = new pck_customComponents.CustomButton();
        btn_nuevoProducto = new pck_customComponents.CustomButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KINT - Dashboard");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_bg.setBackground(new java.awt.Color(245, 245, 245));
        pan_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_menuLatIzq.setBackground(new java.awt.Color(255, 255, 255));

        imgKintLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btn_dashboard.setText("📰 Dashboard");
        btn_dashboard.setToolTipText("Click para ir al Panel Principal");
        btn_dashboard.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_dashboard.setOver(true);
        btn_dashboard.setRadius(30);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        btn_inventario.setText("📦 Inventario");
        btn_inventario.setToolTipText("Click para ver Inventario");
        btn_inventario.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_inventario.setOver(true);
        btn_inventario.setRadius(30);
        btn_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventarioActionPerformed(evt);
            }
        });

        btn_solicitudes.setText("📩  Solicitudes");
        btn_solicitudes.setToolTipText("Click para ver Solicitudes (solo administradores)");
        btn_solicitudes.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_solicitudes.setOver(true);
        btn_solicitudes.setRadius(30);
        btn_solicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitudesActionPerformed(evt);
            }
        });

        btn_usuarios.setText("‍👨 Usuarios");
        btn_usuarios.setToolTipText("Click para ver usuarios (solo administradores)");
        btn_usuarios.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_usuarios.setOver(true);
        btn_usuarios.setRadius(30);
        btn_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariosActionPerformed(evt);
            }
        });

        btn_reportes.setText("📋 Reportes");
        btn_reportes.setToolTipText("Click para ver los Reportes (solo administradores)");
        btn_reportes.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_reportes.setOver(true);
        btn_reportes.setRadius(30);
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });

        btn_ayuda.setText("📞Ayuda");
        btn_ayuda.setToolTipText("Click para ir a ayuda");
        btn_ayuda.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_ayuda.setOver(true);
        btn_ayuda.setRadius(30);
        btn_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ayudaActionPerformed(evt);
            }
        });

        lbl_configuracion.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbl_configuracion.setText("⚙️ ️Configuración");
        lbl_configuracion.setToolTipText("Accede a la configuración general");
        lbl_configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_configuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_configuracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_configuracionMouseExited(evt);
            }
        });

        lbl_logout.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbl_logout.setText("📲 Cerrar Sesión");
        lbl_logout.setToolTipText("Cerrar sesión actual");
        lbl_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pan_menuLatIzqLayout = new javax.swing.GroupLayout(pan_menuLatIzq);
        pan_menuLatIzq.setLayout(pan_menuLatIzqLayout);
        pan_menuLatIzqLayout.setHorizontalGroup(
            pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgKintLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_menuLatIzqLayout.createSequentialGroup()
                        .addGroup(pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_solicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pan_menuLatIzqLayout.setVerticalGroup(
            pan_menuLatIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_menuLatIzqLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(imgKintLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(lbl_configuracion)
                .addGap(18, 18, 18)
                .addComponent(lbl_logout)
                .addContainerGap())
        );

        pan_bg.add(pan_menuLatIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 800));

        pan_cabecera.setBackground(new java.awt.Color(64, 219, 255));
        pan_cabecera.setForeground(new java.awt.Color(99, 101, 105));
        pan_cabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pan_cabeceraMouseDragged(evt);
            }
        });
        pan_cabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pan_cabeceraMousePressed(evt);
            }
        });
        pan_cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_navegador.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        lbl_navegador.setForeground(new java.awt.Color(0, 0, 0));
        lbl_navegador.setText("Inventario /");
        pan_cabecera.add(lbl_navegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 440, 30));

        lbl_exit.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(0, 0, 0));
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.setToolTipText("Salir");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_exitMousePressed(evt);
            }
        });
        pan_cabecera.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 40, 30));

        lbl_icon1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lbl_icon1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_icon1.setText("🏠 / ");
        pan_cabecera.add(lbl_icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        pan_bg.add(pan_cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 1020, 30));

        jSeparator1.setBackground(new java.awt.Color(184, 184, 184));
        jSeparator1.setForeground(new java.awt.Color(184, 184, 184));
        pan_bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 103, 1420, 10));

        lbl_nameholder.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        pan_bg.add(lbl_nameholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 80, 40));

        lbl_userSVG.setToolTipText("Ver perfil");
        lbl_userSVG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pan_bg.add(lbl_userSVG, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 40, 40, 40));

        lbl_username.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lbl_username.setText("Usuario:");
        pan_bg.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 80, 40));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 26, 26));
        jLabel1.setText("Resúmen de productos");

        lbl_icon.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        lbl_icon.setForeground(new java.awt.Color(0, 43, 73));
        lbl_icon.setText(" 📊");

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 26, 26));
        jLabel2.setText("Total de Productos");

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 26, 26));
        jLabel3.setText("Agotados");

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 26, 26));
        jLabel4.setText("Bajos en Stock");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 26), 2, true));

        lbl_agotados.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lbl_agotados.setForeground(new java.awt.Color(26, 26, 26));
        lbl_agotados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_agotados.setText("0");

        lbl_total.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(26, 26, 26));
        lbl_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total.setText("0");

        lbl_stockBajo.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lbl_stockBajo.setForeground(new java.awt.Color(26, 26, 26));
        lbl_stockBajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_stockBajo.setText("0");

        javax.swing.GroupLayout pan_resumenLayout = new javax.swing.GroupLayout(pan_resumen);
        pan_resumen.setLayout(pan_resumenLayout);
        pan_resumenLayout.setHorizontalGroup(
            pan_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_resumenLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pan_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_resumenLayout.createSequentialGroup()
                        .addComponent(lbl_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(pan_resumenLayout.createSequentialGroup()
                        .addGroup(pan_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(pan_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_agotados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(pan_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_stockBajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        pan_resumenLayout.setVerticalGroup(
            pan_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_resumenLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pan_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(pan_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pan_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_agotados)
                    .addComponent(lbl_total)
                    .addComponent(lbl_stockBajo))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pan_bg.add(pan_resumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 400, 190));

        jtable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Acciones"
            }
        ));
        jScrollPane1.setViewportView(jtable_productos);

        javax.swing.GroupLayout panel_productosLayout = new javax.swing.GroupLayout(panel_productos);
        panel_productos.setLayout(panel_productosLayout);
        panel_productosLayout.setHorizontalGroup(
            panel_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_productosLayout.setVerticalGroup(
            panel_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan_bg.add(panel_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 960, 410));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(26, 26, 26));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Filtro de tabla por tipo de producto");

        cb_filtroTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "MATERIAL", "HERRAMIENTA", "DISPOSITIVO" }));
        cb_filtroTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cb_filtroTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_filtroTipoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(26, 26, 26));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Elija que tipo de productos quiere ver:");

        javax.swing.GroupLayout pan_filtroPorTipoLayout = new javax.swing.GroupLayout(pan_filtroPorTipo);
        pan_filtroPorTipo.setLayout(pan_filtroPorTipoLayout);
        pan_filtroPorTipoLayout.setHorizontalGroup(
            pan_filtroPorTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_filtroPorTipoLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(cb_filtroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        pan_filtroPorTipoLayout.setVerticalGroup(
            pan_filtroPorTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_filtroPorTipoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(cb_filtroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pan_bg.add(pan_filtroPorTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 540, 140));

        btn_nuevaCategoria.setText("Categorías");
        btn_nuevaCategoria.setToolTipText("Click para ir al Panel Principal");
        btn_nuevaCategoria.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_nuevaCategoria.setOver(true);
        btn_nuevaCategoria.setRadius(30);
        btn_nuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevaCategoriaActionPerformed(evt);
            }
        });
        pan_bg.add(btn_nuevaCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 120, 40));

        btn_nuevoProducto.setText("+ Nuevo Producto");
        btn_nuevoProducto.setToolTipText("Click para ir al Panel Principal");
        btn_nuevoProducto.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btn_nuevoProducto.setOver(true);
        btn_nuevoProducto.setRadius(30);
        btn_nuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoProductoActionPerformed(evt);
            }
        });
        pan_bg.add(btn_nuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, 170, 40));

        getContentPane().add(pan_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void pan_cabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseinX, y - mouseinY);
    }//GEN-LAST:event_pan_cabeceraMouseDragged

    private void pan_cabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMousePressed
        mouseinX = evt.getX();
        mouseinY = evt.getY();
    }//GEN-LAST:event_pan_cabeceraMousePressed

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        if (!requerirRolPorId(1, 2)) {
            return;
        }
        JOptionPane.showMessageDialog(this, "Redirigiendo a gestión de usuarios.");
    }//GEN-LAST:event_btn_reportesActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        new DashboardView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_inventarioActionPerformed

    private void btn_solicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitudesActionPerformed
        if (!requerirRolPorId(1, 2)) {
            return;
        }
        JOptionPane.showMessageDialog(this, "Redirigiendo a gestión de usuarios.");
    }//GEN-LAST:event_btn_solicitudesActionPerformed

    private void btn_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariosActionPerformed
        if (!requerirRolPorId(1)) {
            return;
        }
        this.dispose();
        new UsersView().setVisible(true);
    }//GEN-LAST:event_btn_usuariosActionPerformed

    private void btn_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ayudaActionPerformed

    private void lbl_configuracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_configuracionMouseEntered
        // TODO add your handling code here:
        lbl_configuracion.setForeground(new java.awt.Color(0, 178, 226));

    }//GEN-LAST:event_lbl_configuracionMouseEntered

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:
        int res;
        res = JOptionPane.showConfirmDialog(null, "¿Desea salir? \n", "Salir", JOptionPane.YES_NO_OPTION);
        if (res == 1) {
            return;
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered
        lbl_exit.setForeground(new java.awt.Color(0, 178, 226));
    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited
        lbl_exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbl_exitMouseExited

    private void lbl_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exitMousePressed

    private void lbl_configuracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_configuracionMouseExited
        lbl_configuracion.setForeground(Color.BLACK);

    }//GEN-LAST:event_lbl_configuracionMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lbl_nameholder.setText(nombreUsuario);
        loadTablaProductosPorTipo("TODOS");
        refreshInventarioView();
        System.out.println(nombreUsuario);
    }//GEN-LAST:event_formWindowActivated

    private void btn_nuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevaCategoriaActionPerformed
        if (!requerirRolPorId(1, 2)) {
            return;
        }
        new CategoriesView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_nuevaCategoriaActionPerformed

    private void cb_filtroTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_filtroTipoActionPerformed
        applyFiltroTipo();
    }//GEN-LAST:event_cb_filtroTipoActionPerformed

    private void btn_nuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoProductoActionPerformed
        if (!requerirRolPorId(1, 2)) {
            return;
        }
        new NewProductView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_nuevoProductoActionPerformed

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        // TODO add your handling code here:
        int aux;
        aux = JOptionPane.showConfirmDialog(this, "¿Desea cerrar sesión?", "Confirmacion", JOptionPane.YES_NO_OPTION);
        if (aux == JOptionPane.YES_OPTION) {
            this.dispose();
            new Login().setVisible(true);
        } else if (aux == JOptionPane.NO_OPTION) {
            return;
        }
    }//GEN-LAST:event_lbl_logoutMouseClicked

    // Autorizacion por ID de rol, la sintaxis de ... hace referencia a un parámetro multivariable, para que pueda poner desde 0...* argumentos
    //útil ya que en lugar de mandar a llamar la función y hacer 3 combinaciones diferentes de arreglos enteros, mejor paso directamente las constantes
    private boolean requerirRolPorId(int... idsPermitidos) {
        if (u == null) {
            JOptionPane.showMessageDialog(this, "Primero inicia sesión.", "Sesión requerida", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        int idRol = u.getIdRol();
        for (int id : idsPermitidos) {
            if (idRol == id) {
                return true;
            }
        }
        JOptionPane.showMessageDialog(this,
                "Solo usuarios autorizados pueden acceder a esta función.\nTu rol: " + u.getRolNombre(),
                "Acceso restringido", JOptionPane.WARNING_MESSAGE);
        return false;
    }

    // --- Acción de filtro ---
    private void applyFiltroTipo() {
        Object sel = cb_filtroTipo.getSelectedItem();
        String tipo = (sel == null) ? "TODOS" : sel.toString().trim();
        loadTablaProductosPorTipo(tipo);
    }

    // --- Cargar tabla según tipo seleccionado ---
    private void loadTablaProductosPorTipo(String tipo) {
        ProductoDAO dao = new ProductoDAO();
        List<ProductoRow> rows = (tipo == null || tipo.equalsIgnoreCase("TODOS"))
                ? dao.listAllBasic()
                : dao.listByTipoBasic(tipo.toUpperCase());

        DefaultTableModel model = construirModeloTablaProductos(rows);
        jtable_productos.setModel(model);
        instalarColumnaAcciones();

        jtable_productos.setAutoCreateRowSorter(true);
        jtable_productos.setRowSelectionAllowed(true);
        jtable_productos.setRowHeight(24);

        TableColumnModel cm = jtable_productos.getColumnModel();
        // Ajusta anchos correctos
        if (cm.getColumnCount() >= 11) {
            cm.getColumn(0).setPreferredWidth(40);   // ID
            cm.getColumn(1).setPreferredWidth(110);  // SKU
            cm.getColumn(2).setPreferredWidth(240);  // Nombre
            cm.getColumn(3).setPreferredWidth(110);  // Tipo
            cm.getColumn(4).setPreferredWidth(140);  // Categoría
            cm.getColumn(5).setPreferredWidth(80);   // U. Medida
            cm.getColumn(6).setPreferredWidth(50);   // Stock
            cm.getColumn(7).setPreferredWidth(120);  // Ubicación
            cm.getColumn(8).setPreferredWidth(70);   // Activo
            cm.getColumn(9).setPreferredWidth(150);  // Creado
            cm.getColumn(10).setPreferredWidth(115); // Acciones
        }
    }

// ---- Refrescar toda la vista ----
    private void refreshInventarioView() {
        cargarResumen();
        cargarTablaSegunTipo();
        formatearTablaProductos();
    }

// ---- Resumen (totales, agotados, bajo stock) ----
    private void cargarResumen() {
        try {
            ProductoDAO dao = new ProductoDAO();
            int total = dao.countAll();
            int agotados = dao.countAgotados();
            int bajos = dao.countBajoStock(UMBRAL_BAJO_STOCK);

            lbl_total.setText(String.valueOf(total));
            lbl_agotados.setText(String.valueOf(agotados));
            lbl_stockBajo.setText(String.valueOf(bajos));
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "No se pudo cargar el resumen de inventario.\n" + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

// ---- Determinar el tipo seleccionado en el Cb (TODOS | MATERIAL | HERRAMIENTA | DISPOSITIVO) ----
    private String getTipoSeleccionado() {
        Object val = cb_filtroTipo.getSelectedItem();
        if (val == null) {
            return "TODOS";
        }
        String s = val.toString().trim().toUpperCase();
        if (s.equals("MATERIAL") || s.equals("HERRAMIENTA") || s.equals("DISPOSITIVO")) {
            return s;
        }
        return "TODOS";
    }

// ----Cargar tabla según el filtro de tipo ----
    private void cargarTablaSegunTipo() {
        try {
            String tipo = getTipoSeleccionado();
            ProductoDAO dao = new ProductoDAO();

            List<ProductoRow> rows;
            if ("TODOS".equals(tipo)) {
                rows = dao.listAllBasic();           // SELECT de columnas para tabla
            } else {
                rows = dao.listByTipoBasic(tipo);    // SELECT filtrado por tipo
            }

            DefaultTableModel model = construirModeloTablaProductos(rows);
            jtable_productos.setModel(model);
            instalarColumnaAcciones();

            if (model.getRowCount() == 0) {
                mostrarEstadoVacioEnTabla(model);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "No se pudo cargar la tabla de productos.\n" + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

// ---- Construir el TableModel que se asigna a jtable_productos ----
    private DefaultTableModel construirModeloTablaProductos(List<ProductoRow> rows) {
        String[] cols = {
            "ID", "SKU", "Nombre", "Tipo", "Categoría",
            "U. Medida", "Stock", "Ubicación", "Activo", "Creado", "Acciones"
        };

        DefaultTableModel model = new DefaultTableModel(cols, 0) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return c == 10;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return Integer.class;         // ID
                    case 6:
                        return Integer.class;         // Stock
                    default:
                        return String.class;
                }
            }
        };

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        if (rows != null) {
            for (ProductoRow r : rows) {
                String creado = (r.getFechaCreacion() == null) ? "" : sdf.format(r.getFechaCreacion());
                model.addRow(new Object[]{
                    r.getIdProducto(),
                    r.getSku(),
                    r.getNombre(),
                    r.getTipo(),
                    r.getCategoria(),
                    r.getUMedida(),
                    r.getStock(),
                    r.getUbicacion(),
                    r.isActivo() ? "Sí" : "No",
                    creado,
                    null
                });
            }
        }
        return model;
    }
// ---- Formato visual y mejoras de usabilidad de la tabla ----

    private void formatearTablaProductos() {
        jtable_productos.setAutoCreateRowSorter(true);
        jtable_productos.setRowHeight(22);
        jtable_productos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // Anchos  
        TableColumnModel cm = jtable_productos.getColumnModel();
        if (cm.getColumnCount() >= 10) {
            cm.getColumn(0).setPreferredWidth(40);   // ID
            cm.getColumn(1).setPreferredWidth(110);  // SKU
            cm.getColumn(2).setPreferredWidth(220);  // Nombre
            cm.getColumn(3).setPreferredWidth(110);  // Tipo
            cm.getColumn(4).setPreferredWidth(150);  // Categoría
            cm.getColumn(5).setPreferredWidth(90);   // U. Medida
            cm.getColumn(6).setPreferredWidth(50);   // Stock
            cm.getColumn(7).setPreferredWidth(140);  // Ubicación
            cm.getColumn(8).setPreferredWidth(70);   // Activo
            cm.getColumn(9).setPreferredWidth(140);  // Creado
            cm.getColumn(10).setPreferredWidth(115);  // Creado
        }
    }

// ---- Estado vacío en la tabla  ----
    private void mostrarEstadoVacioEnTabla(DefaultTableModel model) {
        model.addRow(new Object[]{
            "—", "—", "No hay productos registrados.", "—", "—",
            "—", "—", "—", "—", "—"
        });
        jtable_productos.setModel(model);
        instalarColumnaAcciones();
        jtable_productos.setAutoCreateRowSorter(false);
        jtable_productos.setRowSelectionAllowed(false);
        jtable_productos.setEnabled(false);

        DefaultTableCellRenderer gray = new DefaultTableCellRenderer();
        gray.setForeground(new Color(120, 120, 120));
        gray.setFont(jtable_productos.getFont().deriveFont(Font.ITALIC));
        jtable_productos.getColumnModel().getColumn(2).setCellRenderer(gray); 
    }

    private void instalarColumnaAcciones() {
        int idx = jtable_productos.getColumnModel().getColumnIndex("Acciones");

        jtable_productos.getColumnModel().getColumn(idx)
                .setCellRenderer(new AccionesRenderer(true));

        jtable_productos.getColumnModel().getColumn(idx).setCellEditor(
                new AccionesEditor(
                        jtable_productos,
                        0,
                        new AccionesHandler() {
                    @Override
                    public void editar(int idProducto, int modelRow) {
                        onEditarProducto(idProducto, modelRow);
                    }

                    @Override
                    public void eliminar(int idProducto, int modelRow) {
                        onEliminarProducto(idProducto, modelRow);
                    }

                    @Override
                    public void solicitar(int idProducto, int modelRow) {
                    }
                },
                        true
                )
        );

        jtable_productos.getColumnModel().getColumn(idx).setPreferredWidth(115);
        jtable_productos.setRowHeight(24);
    }

    private void onEditarProducto(int idProducto, int modelRow) {
        if (!requerirRolPorId(1, 2)) {
            return;
        } else {
            new EditProductView(idProducto).setVisible(true);
            this.dispose();
            JOptionPane.showMessageDialog(this, "Editar producto ID: " + idProducto);
        }

    }

    private void onEliminarProducto(int idProducto, int modelRow) {
        if (!requerirRolPorId(1, 2)) {
            return;
        } else {
            int res = JOptionPane.showConfirmDialog(this,
                    "¿Seguro que deseas eliminar el producto ID " + idProducto + "?",
                    "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (res != JOptionPane.YES_OPTION) {
                return;
            }

            ProductoDAO dao = new ProductoDAO();
            boolean ok = dao.deleteHard(idProducto); //
            if (ok) {
                ((DefaultTableModel) jtable_productos.getModel()).removeRow(modelRow);
                cargarResumen();
                JOptionPane.showMessageDialog(this, "Producto eliminado.");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar. Revise las relaciones con otras tablas como proveedores o prestamos activos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    private void onFiltroTipoChanged() {
        cargarTablaSegunTipo();
        formatearTablaProductos();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryView().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pck_customComponents.CustomButton btn_ayuda;
    private pck_customComponents.CustomButton btn_dashboard;
    private pck_customComponents.CustomButton btn_inventario;
    private pck_customComponents.CustomButton btn_nuevaCategoria;
    private pck_customComponents.CustomButton btn_nuevoProducto;
    private pck_customComponents.CustomButton btn_reportes;
    private pck_customComponents.CustomButton btn_solicitudes;
    private pck_customComponents.CustomButton btn_usuarios;
    private javax.swing.JComboBox<String> cb_filtroTipo;
    private javax.swing.JLabel imgKintLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtable_productos;
    private javax.swing.JLabel lbl_agotados;
    private javax.swing.JLabel lbl_configuracion;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_icon1;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_nameholder;
    private javax.swing.JLabel lbl_navegador;
    private javax.swing.JLabel lbl_stockBajo;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_userSVG;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pan_bg;
    private javax.swing.JPanel pan_cabecera;
    private pck_customComponents.RoundedPanel pan_filtroPorTipo;
    private javax.swing.JPanel pan_menuLatIzq;
    private pck_customComponents.RoundedPanel pan_resumen;
    private pck_customComponents.RoundedPanel panel_productos;
    // End of variables declaration//GEN-END:variables
}
