/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pck_GUIs;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author dieca
 */
public class Login extends javax.swing.JFrame {

    int mouseinX, mouseinY;
    Rescalar escalar = new Rescalar();

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                tf_showPass.setVisible(false);
                escalar.escalarLabel(imgKintLogo, "/pck_img/kintLogo.png");
                escalar.escalarLabel(imgLogin, "/pck_img/imgLogin.png");
            }
        });
        
        tf_pass.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { sync(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { sync(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { sync(); }

            private void sync() {
                if (cb_showPassword.isSelected()) {
                    tf_showPass.setText(new String(tf_pass.getPassword()));
                }
            }
        });

        // 2) Re-escala si los labels cambian de tamaño
        java.awt.event.ComponentAdapter resizeListener = new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                if (e.getComponent() == imgKintLogo) {
                    escalar.escalarLabel(imgKintLogo, "/pck_img/kintLogo.png");
                } else if (e.getComponent() == imgLogin) {
                    escalar.escalarLabel(imgLogin, "/pck_img/imgLogin.png");
                }
            }
        };
        imgKintLogo.addComponentListener(resizeListener);
        imgLogin.addComponentListener(resizeListener);

        setIconImage(new ImageIcon(getClass().getResource("/pck_img/favicon.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_background = new javax.swing.JPanel();
        imgKintLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imgLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 700), new java.awt.Dimension(0, 700), new java.awt.Dimension(32767, 700));
        lbl_password = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        tf_pass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_user = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        pan_cabecera = new javax.swing.JPanel();
        btn_login = new pck_customComponents.CustomButton();
        cb_showPassword = new javax.swing.JCheckBox();
        tf_showPass = new pck_customComponents.RoundedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KINT - Login");
        setUndecorated(true);
        setResizable(false);

        pan_background.setBackground(new java.awt.Color(240, 240, 240));
        pan_background.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        pan_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgKintLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pan_background.add(imgKintLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 320, 110));

        jPanel2.setBackground(new java.awt.Color(0, 43, 73));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogin.setBackground(new java.awt.Color(64, 219, 255));
        imgLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogin.setToolTipText("");
        jPanel2.add(imgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 400, 370));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 184, 16));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicia sesión y ordena eficázmente");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 540, 30));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Controla el inventario ágilmente,");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 540, 30));

        pan_background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 550, 700));

        filler3.setBackground(new java.awt.Color(0, 178, 226));
        filler3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 178, 226), 10));
        filler3.setForeground(new java.awt.Color(0, 0, 0));
        pan_background.add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 10, 700));

        lbl_password.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(0, 0, 0));
        lbl_password.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_password.setText("CONTRASEÑA");
        pan_background.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 140, 30));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 43, 73));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("IN");
        pan_background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 60, 40));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 178, 226));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LOG");
        pan_background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 40));

        tf_user.setBackground(new java.awt.Color(240, 240, 240));
        tf_user.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tf_user.setForeground(new java.awt.Color(153, 153, 153));
        tf_user.setText("Ingrese su nombre de usuario");
        tf_user.setToolTipText("Ingrese su nombre de usuario");
        tf_user.setBorder(null);
        tf_user.setNextFocusableComponent(tf_pass);
        tf_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_userFocusGained(evt);
            }
        });
        tf_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tf_userMousePressed(evt);
            }
        });
        tf_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_userActionPerformed(evt);
            }
        });
        pan_background.add(tf_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 230, 20));
        pan_background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 230, 10));

        tf_pass.setBackground(new java.awt.Color(240, 240, 240));
        tf_pass.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        tf_pass.setForeground(new java.awt.Color(153, 153, 153));
        tf_pass.setText("********************");
        tf_pass.setToolTipText("Ingrese su contraseña");
        tf_pass.setBorder(null);
        tf_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_passFocusGained(evt);
            }
        });
        tf_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tf_passMousePressed(evt);
            }
        });
        tf_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passActionPerformed(evt);
            }
        });
        pan_background.add(tf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 230, 20));
        pan_background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 230, 10));

        lbl_user.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(0, 0, 0));
        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_user.setText("USUARIO (CORREO ELECTRÓNICO)");
        pan_background.add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 230, 30));

        lbl_exit.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(0, 0, 0));
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.setToolTipText("Salir");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_exitMousePressed(evt);
            }
        });
        pan_background.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, 30));

        pan_cabecera.setBackground(new java.awt.Color(64, 219, 255));
        pan_cabecera.setForeground(new java.awt.Color(99, 101, 105));
        pan_cabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pan_cabeceraMouseDragged(evt);
            }
        });
        pan_cabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pan_cabeceraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pan_cabeceraLayout = new javax.swing.GroupLayout(pan_cabecera);
        pan_cabecera.setLayout(pan_cabeceraLayout);
        pan_cabeceraLayout.setHorizontalGroup(
            pan_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        pan_cabeceraLayout.setVerticalGroup(
            pan_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pan_background.add(pan_cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 30));

        btn_login.setBackground(new java.awt.Color(0, 43, 73));
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Entrar");
        btn_login.setColor(new java.awt.Color(0, 43, 73));
        btn_login.setColorOver(new java.awt.Color(0, 43, 73));
        btn_login.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btn_login.setFontColorOver(new java.awt.Color(255, 255, 255));
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loginMouseExited(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        pan_background.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 90, 40));

        cb_showPassword.setFont(new java.awt.Font("Nirmala UI", 0, 10)); // NOI18N
        cb_showPassword.setText("MOSTRAR CONTRASEÑA");
        cb_showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_showPasswordActionPerformed(evt);
            }
        });
        pan_background.add(cb_showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 150, 30));

        tf_showPass.setEditable(false);
        tf_showPass.setEnabled(false);
        tf_showPass.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        tf_showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_showPassActionPerformed(evt);
            }
        });
        pan_background.add(tf_showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_userActionPerformed

    private void tf_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passActionPerformed
    }//GEN-LAST:event_tf_passActionPerformed

    private void pan_cabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMousePressed
        mouseinX = evt.getX();
        mouseinY = evt.getY();
    }//GEN-LAST:event_pan_cabeceraMousePressed

    private void pan_cabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseinX, y - mouseinY);
    }//GEN-LAST:event_pan_cabeceraMouseDragged

    private void lbl_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exitMousePressed

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:
        int res;
        res = JOptionPane.showConfirmDialog(this, "¿Desea salir? \n", "Salir", JOptionPane.YES_NO_OPTION);
        if (res == 1) {
            return;
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered
        lbl_exit.setForeground(new java.awt.Color(0, 178, 226));
    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited
        lbl_exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbl_exitMouseExited

    private void tf_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_userMousePressed
        if (tf_user.getText().equals("Ingrese su nombre de usuario")) {
            tf_user.setText("");
            tf_user.setForeground(Color.BLACK);
        }
        if (String.valueOf(tf_pass.getPassword()).isEmpty()) {
            tf_pass.setText("********************");
            tf_pass.setForeground(new java.awt.Color(153, 153, 153));
        }


    }//GEN-LAST:event_tf_userMousePressed

    private void tf_passMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_passMousePressed
        if (String.valueOf(tf_pass.getPassword()).equals("********************")) {
            tf_pass.setText("");
            tf_pass.setForeground(Color.BLACK);
        }
        if (tf_user.getText().isEmpty()) {
            tf_user.setText("Ingrese su nombre de usuario");
            tf_user.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_tf_passMousePressed

    private void btn_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseExited
        btn_login.setForeground(Color.white);
    }//GEN-LAST:event_btn_loginMouseExited

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        loggear();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void tf_userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_userFocusGained
        if (!(tf_user.getText().equals("") || tf_user.getText().equals("Ingrese su nombre de usuario"))) {
        } else {
            tf_user.setForeground(Color.black);
            tf_user.setText("");
            if (tf_user.getText().equals("Ingrese su nombre de usuario")) {
                tf_user.setText("");
                tf_user.setForeground(Color.BLACK);
            }
            if (String.valueOf(tf_pass.getPassword()).isEmpty()) {
                tf_pass.setText("********************");
                tf_pass.setForeground(new java.awt.Color(153, 153, 153));
            }
        }

    }//GEN-LAST:event_tf_userFocusGained

    private void tf_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_passFocusGained
        if (!(String.valueOf(tf_pass.getPassword()).equals("") || String.valueOf(tf_pass.getPassword()).equals("********************"))) {
        } else {
            tf_pass.setForeground(Color.black);
            tf_pass.setText("");
            if (String.valueOf(tf_pass.getPassword()).equals("********************")) {
                tf_pass.setText("");
                tf_pass.setForeground(Color.BLACK);
            }
            if (tf_user.getText().isEmpty()) {
                tf_user.setText("Ingrese su nombre de usuario");
                tf_user.setForeground(new java.awt.Color(153, 153, 153));
            }
        }
    }//GEN-LAST:event_tf_passFocusGained

    private void cb_showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_showPasswordActionPerformed
        // TODO add your handling code here:
        if (cb_showPassword.isSelected()) {
            tf_showPass.setVisible(true);
            tf_showPass.setText(new String(tf_pass.getPassword())); 
        } else {
            tf_showPass.setVisible(false);
        }
    }//GEN-LAST:event_cb_showPasswordActionPerformed

    private void tf_showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_showPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_showPassActionPerformed
    
    private void loggear() {
        String correo = tf_user.getText().trim();
        char[] passChars = tf_pass.getPassword();
        if (correo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese su correo.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (passChars.length == 0) {
            JOptionPane.showMessageDialog(this, "Ingrese su contraseña.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            pck_dao.UsuarioDAO dao = new pck_dao.UsuarioDAO();
            pck_model.Usuario u = dao.findByCorreo(correo);

            if (u == null) {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado o inactivo.", "Login", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String passIngresado = new String(passChars);
            String hashIngresado = pck_security.HashUtil.sha256Hex(passIngresado);

            if (hashIngresado.equalsIgnoreCase(u.getContrasenaHash())) {
                pck_service.Session.login(u); //se guarda en "sesion" el usuario
                JOptionPane.showMessageDialog(this, "Bienvenido, " + u.getNombre() + ".", "Éxito al iniciar sesión", JOptionPane.INFORMATION_MESSAGE);
                new pck_GUIs.DashboardView().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Contraseña incorrecta.", "Login", JOptionPane.ERROR_MESSAGE);
                tf_pass.setText("");
                tf_pass.requestFocusInWindow();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "No se pudo validar en la BD.\nDetalle: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            java.util.Arrays.fill(passChars, '\0'); //borra el pass de la memoria
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pck_customComponents.CustomButton btn_login;
    private javax.swing.JCheckBox cb_showPassword;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel imgKintLogo;
    private javax.swing.JLabel imgLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JPanel pan_background;
    private javax.swing.JPanel pan_cabecera;
    private javax.swing.JPasswordField tf_pass;
    private pck_customComponents.RoundedTextField tf_showPass;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
}
