/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pck_GUIs;

import java.awt.Color;
import static java.awt.Color.WHITE;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author dieca
 */
public class PassRecover extends javax.swing.JFrame {

    int mouseinX, mouseinY;
    Rescalar escalar = new Rescalar();

    /**
     * Creates new form login
     */
    public PassRecover() {
        initComponents();
        setLocationRelativeTo(null);
        escalar.escalarLabel(imgKintLogo, "/pck_img/kintLogo.png");
        escalar.escalarLabel(imgLogin, "/pck_img/imgLogin.png");
        setIconImage(new ImageIcon(getClass().getResource("/pck_img/favicon.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_background = new javax.swing.JPanel();
        imgKintLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imgLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 700), new java.awt.Dimension(0, 700), new java.awt.Dimension(32767, 700));
        lbl_password = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        lbl_recuperar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tf_pass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        tf_entrar = new javax.swing.JLabel();
        pan_entrar = new javax.swing.JPanel();
        lbl_user = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        pan_cabecera = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KINT - Recuperación de contraseña");
        setUndecorated(true);
        setResizable(false);

        pan_background.setBackground(new java.awt.Color(240, 240, 240));
        pan_background.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        pan_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgKintLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pan_background.add(imgKintLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 320, 110));

        jPanel2.setBackground(new java.awt.Color(0, 43, 73));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogin.setToolTipText("");
        jPanel2.add(imgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 400, 370));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 184, 16));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicia sesión y ordena eficázmente");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 540, 30));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Controla el inventario ágilmente,");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 540, 30));

        pan_background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 550, 700));

        filler3.setBackground(new java.awt.Color(0, 178, 226));
        filler3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 178, 226), 10));
        filler3.setForeground(new java.awt.Color(0, 0, 0));
        pan_background.add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 10, 700));

        lbl_password.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(0, 0, 0));
        lbl_password.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_password.setText("CONTRASEÑA");
        pan_background.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 140, 30));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 43, 73));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pan_background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, 40));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 178, 226));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RECUPERACIÓN");
        pan_background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 40));

        tf_user.setBackground(new java.awt.Color(240, 240, 240));
        tf_user.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tf_user.setForeground(new java.awt.Color(153, 153, 153));
        tf_user.setText("Ingrese su nombre de usuario");
        tf_user.setToolTipText("Ingrese su nombre de usuario");
        tf_user.setBorder(null);
        tf_user.setNextFocusableComponent(tf_pass);
        tf_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tf_userMousePressed(evt);
            }
        });
        tf_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_userActionPerformed(evt);
            }
        });
        pan_background.add(tf_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 230, 20));

        lbl_recuperar.setFont(new java.awt.Font("Nirmala UI", 1, 10)); // NOI18N
        lbl_recuperar.setForeground(new java.awt.Color(0, 178, 226));
        lbl_recuperar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_recuperar.setText("Olvidé mi contraseña");
        lbl_recuperar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pan_background.add(lbl_recuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 190, 10));
        pan_background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 230, 10));

        tf_pass.setBackground(new java.awt.Color(240, 240, 240));
        tf_pass.setForeground(new java.awt.Color(153, 153, 153));
        tf_pass.setText("********************");
        tf_pass.setToolTipText("Ingrese su contraseña");
        tf_pass.setBorder(null);
        tf_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tf_passMousePressed(evt);
            }
        });
        tf_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passActionPerformed(evt);
            }
        });
        pan_background.add(tf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 230, 20));
        pan_background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 230, 10));

        tf_entrar.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        tf_entrar.setForeground(new java.awt.Color(255, 255, 255));
        tf_entrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tf_entrar.setText("Entrar");
        tf_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pan_background.add(tf_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 100, 40));

        pan_entrar.setBackground(new java.awt.Color(0, 43, 73));
        pan_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pan_entrarLayout = new javax.swing.GroupLayout(pan_entrar);
        pan_entrar.setLayout(pan_entrarLayout);
        pan_entrarLayout.setHorizontalGroup(
            pan_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pan_entrarLayout.setVerticalGroup(
            pan_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pan_background.add(pan_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, 40));

        lbl_user.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(0, 0, 0));
        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_user.setText("CORREO");
        pan_background.add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 80, 30));

        lbl_exit.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.setToolTipText("Salir");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_exitMousePressed(evt);
            }
        });
        pan_background.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, 30));

        pan_cabecera.setBackground(new java.awt.Color(64, 219, 255));
        pan_cabecera.setForeground(new java.awt.Color(99, 101, 105));
        pan_cabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pan_cabeceraMouseDragged(evt);
            }
        });
        pan_cabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pan_cabeceraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pan_cabeceraLayout = new javax.swing.GroupLayout(pan_cabecera);
        pan_cabecera.setLayout(pan_cabeceraLayout);
        pan_cabeceraLayout.setHorizontalGroup(
            pan_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        pan_cabeceraLayout.setVerticalGroup(
            pan_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pan_background.add(pan_cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_userActionPerformed

    private void tf_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_passActionPerformed

    private void pan_cabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMousePressed
        mouseinX = evt.getX();
        mouseinY = evt.getY();
    }//GEN-LAST:event_pan_cabeceraMousePressed

    private void pan_cabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_cabeceraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseinX, y - mouseinY);
    }//GEN-LAST:event_pan_cabeceraMouseDragged

    private void lbl_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exitMousePressed

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:
        int res;
        res = JOptionPane.showConfirmDialog(null, "¿Desea salir? \n", "Salir", JOptionPane.YES_NO_OPTION);
        if (res == 1) {
            return;
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered
        lbl_exit.setForeground(new java.awt.Color(0, 178, 226));
    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited
        lbl_exit.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbl_exitMouseExited

    private void tf_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_userMousePressed
        if (tf_user.getText().equals("Ingrese su nombre de usuario")) {
            tf_user.setText("");
            tf_user.setForeground(Color.BLACK);
        }
        if (String.valueOf(tf_pass.getPassword()).isEmpty()) {
            tf_pass.setText("********************");
            tf_pass.setForeground(new java.awt.Color(153, 153, 153));
        }


    }//GEN-LAST:event_tf_userMousePressed

    private void tf_passMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_passMousePressed
        if (String.valueOf(tf_pass.getPassword()).equals("********************")) {
            tf_pass.setText("");
            tf_pass.setForeground(Color.BLACK);
        }
        if (tf_user.getText().isEmpty()) {
            tf_user.setText("Ingrese su nombre de usuario");
            tf_user.setForeground(new java.awt.Color(153, 153, 153));
        }


    }//GEN-LAST:event_tf_passMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassRecover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassRecover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassRecover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassRecover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassRecover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel imgKintLogo;
    private javax.swing.JLabel imgLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_recuperar;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JPanel pan_background;
    private javax.swing.JPanel pan_cabecera;
    private javax.swing.JPanel pan_entrar;
    private javax.swing.JLabel tf_entrar;
    private javax.swing.JPasswordField tf_pass;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
}
